### ISSUE TITLE
Tint2 position problem

### ISSUE THREAD

**Issue by Spider-Jerusalem** [lanoxx/tilda#101]
I don't know if it's an issue, and if I'm alone with this "problem", but even at position Y=0, tilda can't go over tint2 while guake and yakuake can perform this perfectly.

Here's a picture of the "problem": http://a.pomf.se/twuanu.png

**Comment by lanoxx** [comment]
That is caused by your window manager, nothing tilda can do about it. Same thing on Gnome Shell.
