### ISSUE TITLE
Call Tilde to Display with Shell Command (Feature Request)

### ISSUE THREAD

**Issue by theNerd247** [lanoxx/tilda#102]
I use ncmpcpp (for music) and mutt (for mail) (along with some other terminal based utilities) in openbox. It would be wonderful if I could perform: 

       $ tilda -e "exec ncmpcpp"  --> shows tilda and opens ncmpcpp in tilda

Where `-e` would show tilda and run the command in the shell. This would give tilda some great extensibility as far as end user integration into their DW/WM.

Great program btw!

**Comment by paulie-g** [comment]
That's what the -c/--command command line option is for, unless I'm missing something.

**Comment by theNerd247** [comment]
yup! that's it. Sorry to clog up the issues...
