### ISSUE TITLE
Move tab left keybinding does not work and labels are wrong

### ISSUE THREAD

**Issue by bnkr** [lanoxx/tilda#104]
I'm not sure if I've broken my build somehow but since upgrading to latest master my move tab left keybind doesn't work any more.

Also the names are the wrong way round!  This seems to have been the case in previous revisions to but I didn't notice it.

I bind "<primary><shift>Right" to move tab left (sic) (using crtl+shift+right arrow in the preferences window).  And <primary><shift>Left to move tab right (sic)with the same method.

These entries are in the config::

    movetableft_key = "<Primary><Shift>Right"
    movetabright_key = "<Primary><Shift>Left"

To reproduce just activate tilda and press ctrl+shift+right then ctrl+shift+left.  Only the rightwards movement will work.

**Comment by lanoxx** [comment]
Fixed by 6ef586f3ff552d1f245877bc84274230db9f2dde
