### ISSUE TITLE
pull toggle (<F2>) doesn't work when auto-hide enabled

### ISSUE THREAD

**Issue by dweymouth** [lanoxx/tilda#106]
Steps to reproduce (tested on Linux Mint 17 Cinnamon, 64-bit):
1. Ensure that the "Hide when Tilda loses focus" option is enabled
2. Press <F2> to pull down Tilda initially
3. Click in another window to cause it to auto-hide
4. Press <F2> to pull down Tilda again
5. Without unfocusing, press <F2> again. This _should_ pull up the terminal, but instead does one of these two things:
- pulls up the terminal briefly before bringing it back down again
- pulls the terminal up, then down, then up again (less common)

This bug is present in the latest git-master, version 1.2.2

**Comment by pik** [comment]
I'm having quite a few other bugs while testing auto-hide as well (it's not something I normally use). @lanoxx Is there a plan to deprecate this feature or should it be maintained?

**Comment by lanoxx** [comment]
@pik Sorry that I never replied to your question. Somehow it got lost in the bug tracker.

There were a few changes to the pull behavior and at them moment I cannot reproduce this bug. If its possible to reproduce it with the latest version, feel free to reopen this bug.
