### ISSUE TITLE
Open in terminal

### ISSUE THREAD

**Issue by komitaltrade** [lanoxx/tilda#107]
I think that this is the "bug".

If one instance of tilda is opened (to be more clear, with solarized scheme) and tilda is default terminal, when user make right click in file manager to open folder in terminal, tildaa is open correctly, but like new default instance (small and black scheme), instead in new teb.

To be more clear, if tilda is not activ and user do the same right click, tilda correctly open default (custom.new) solarized scheme instance (path is allways fine/correct).

**Comment by lanoxx** [comment]
Duplicate issue: #145
