### ISSUE TITLE
src/tilda_terminal.c:677: possible bad if test ?

### ISSUE THREAD

**Issue by dcb314** [lanoxx/tilda#118]
[src/tilda_terminal.c:677]: (warning) Char literal compared with pointer 'word_chars'. Did you intend to dereference it?

Source code is

    if (NULL == word_chars || '\0' == word_chars)
        word_chars = DEFAULT_WORD_CHARS;

Maybe

    if (NULL == word_chars || '\0' == *word_chars)
        word_chars = DEFAULT_WORD_CHARS;

was intended.

**Comment by lanoxx** [comment]
Your analysis looks correct. I will fix this. Note that most of the code is very old and I have not touched every line of code yet. So suggestions and error reports are always welcome. Thank you.
