### ISSUE TITLE
Tilda always on monitor 0 with marco (MATE)

### ISSUE THREAD

**Issue by dschwoerer** [lanoxx/tilda#119]
I dont know whether this is a bug in tilda or marco (https://github.com/mate-desktop/marco)
But tilda apears always on monitor 0, even if monitor 1 is selected in the preferences.
Switching to metacity resolves the issue.

**Comment by lanoxx** [comment]
If it works with Metacity and not with Marco then this is a strong indicator that there is a bug in Marco. Maybe Marco reports wrong geometry information about the monitors to tilda. I recommend to report the bug on the marco bug tracker.

There are a few monitor related issues in marco: https://github.com/mate-desktop/marco/issues?q=is%3Aissue+is%3Aopen+monitor
