### ISSUE TITLE
Add support for using Tilda as a desktop (aka transparent wallpaper) terminal

### ISSUE THREAD

**Issue by paulie-g** [lanoxx/tilda#123]
Here's an (ugly) example: http://i.hmp.me/m/4eb8a88b8533e386f2321f4f58f4e2c2.png

Tilda is almost perfect for this as-is, with one exception: "toggle show desktop" and similar (eg Super-D by default in openbox) will hide it, whereas the desired behaviour is for it to remain and receive focus.

In order to persist across "toggle show desktop" functionality invocations in
ICCCM/EWMH compliant window managers, an application needs to set the 
_NET_WM_WINDOW_TYPE hint for the window in question to _NET_WM_WINDOW_TYPE_DESKTOP
before it's mapped in. While a couple of other kludges enable such a use case on
specific WMs in other ways (eg Dock window type hint handling abuse), this should enable Tilda to do it on all compliant WMs without interfering with docks/launchers/etc. Incidentally, it would be the first to have such support afaik/ct. Not everyone wants to do it, but the people who want to do it *really* want to.

A pull request will be coming in shortly adding this feature, configurable in the config or by means of the wizard. Defaults to no, obviously.

**Comment by lanoxx** [comment]
Closed by commit: 55164e2761368127fa01835279ef0e5c6fabbe11
