### ISSUE TITLE
Tilda on FreeBSD 10.1

### ISSUE THREAD

**Issue by mzs114** [lanoxx/tilda#130]
Hello we have an open PR for upgrading tilda on FreeBSD. FreeBSD users are still using 0.9.6 version since 2008.
The maintainer is trying to build version 1.2, but is unable to. 
So would like to know the probable release date for version 1.3 and whether we can expect it to build on FreeBSD or what modifications are necessary.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198763

Thanks!

**Comment by lanoxx** [comment]
Hi mzs,
    
    could you explain in more detail what is the problem with building
    version 1.2 on BSD? You need to compile and build against libvte
    2.90 (version 0.34 or below)? When I check the FreeBSD ports
    section, then I see there exists vte3-290-0.34.7_1:
    
     http://svnweb.freebsd.org/ports/head/x11-toolkits/vte290/
    
    This should work in my opinion. Porting tilda to VTE 2.91 is not so
    simple, for several reasons. I do have plans to do this eventually
    but I will try to support both 2.90 and 2.91 APIs and currently I
    have no time to make those changes.
    
    Anyway, if try to build with the above mentioned library and it
    still does not work, then please let me know and I will see what I
    can do to fix any issues.
    
    Regards
    Sebastian
    
    On 25/03/15 15:01, mzs114 wrote:
    
    
      Hello we have an open PR for upgrading tilda on FreeBSD.
        FreeBSD users are still using 0.9.6 version since 2008.
        The maintainer is trying to build version 1.2, but is unable to.
        
        So would like to know the probable release date for version 1.3
        and whether we can expect it to build on FreeBSD or what
        modifications are necessary.
      https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198763
      Thanks!
      —
        Reply to this email directly or view it on
          GitHub.

**Comment by mzs114** [comment]
I have requested the maintainer to join.
Thanks for the speedy response :)

**Comment by rosorio** [comment]
I found a solution, a pkg for test is on the way

**Comment by mzs114** [comment]
@rosorio Nice!

**Comment by mzs114** [comment]
@rosorio Thank you for updating tilda, I am now running version 1.2.2.

@lanoxx Thank you for developing tilda, I depend on this for my day to day activities.

I guess we can close this issue.

**Comment by NitroNils** [comment]
I'm running
```
> tilda --version
Tilda 1.5.0
```
on FreeBSD 12.2 now. GhostBSD
