### ISSUE TITLE
Can not load config_0

### ISSUE THREAD

**Issue by acgtyrant** [lanoxx/tilda#137]
I linked `dotfiles/Tilda/.config/tilda/config_0` to `.config/tilda/config`, but the tilda does not load this config, i have removed the `config_1`, there is only `config_0` in `.config/tilda`.

**Comment by lanoxx** [comment]
I dont know what you mean by `dotfiles/Tilda` Anyway each config file must end with an underscore and a number 0 to n, there will always be one config file for each instance that is running. Why are you creating symlinks to the config files in the first place?

**Comment by acgtyrant** [comment]
I would like to backup tilda's config and store it in `https://github.com/acgtyrant/dotfiles`, I can [restore this config via `stow Tilda`](http://brandon.invergo.net/news/2012-05-26-using-gnu-stow-to-manage-your-dotfiles.html).

However, I reinstalled my Arch Linux and restore this config, I noticed that there is `config_1`, but Tilda still does no load `config_0` after I removed `config_1`.

**Comment by acgtyrant** [comment]
Sorry for my typo in the first post, it is "I linked `dotfiles/Tilda/.config/tilda/config_0` to `.config/tilda/config_0`" exactly.

**Comment by lanoxx** [comment]
The first tilda process you start will load its config from `config_0`, if you start tilda a second time, it will load its config from `config_1` and so one. If you create a symlink from

`~/.config/tilda/config_0 -> ~/some/other/place/config_0` then tilda should read it.

**Comment by lanoxx** [comment]
Here is an example from my `~/.config/tilda` folder:

    -rw-rw-r--  1 myusr mygrp 2.1K Apr 10 17:41 config
    lrwxrwxrwx  1 myusr mygrp    6 Apr 10 17:40 config_0 -> config

**Comment by lanoxx** [comment]
I am closing this issue as I think this is not a problem in tilda.

**Comment by acgtyrant** [comment]
You are right, I find my `config_0` is covered by a new default `config_0` which is created by Tilda actually...

I will remove this `config_0` and link my backup again.
