### ISSUE TITLE
hidding tilda makes the terminal report wrong size

### ISSUE THREAD

**Issue by voidplayer** [lanoxx/tilda#14]
This is a simple guess of what happens

Weechat layout is lost down to one window when size of the terminal cant hold all the splits windows.

After hidding terminal with hotkey and go back again, layout is gone. Probably due to terminal reporting wrong size when hidded

This is reproducible

**Comment by lanoxx** [comment]
With the latest 1.3 release the animation code was rewritten to not resize the tilda window anymore. So this should be fixed. If you can still reproduce this problem with 1.3 or later, then please reopen.
