### ISSUE TITLE
Missing call to free? 

### ISSUE THREAD

**Issue by pik** [lanoxx/tilda#141]
https://github.com/lanoxx/tilda/blob/master/src/wizard.c#L656 Should this be freed before the function returns? Every single callback is allocating for a new rect.

**Comment by lanoxx** [comment]
Yes you are correct. That memory needs to be freed.
    
    On 18/04/15 07:03, Alex wrote:
    
    
      https://github.com/lanoxx/tilda/blob/master/src/wizard.c#L656
        Should this be freed before the function returns? Every single
        callback is allocating a new rect. 
      —
        Reply to this email directly or view it on
          GitHub.

**Comment by lanoxx** [comment]
Fixed by c661eb86f0c1b05a690ecb1376f2eddc8debc6d3
