### ISSUE TITLE
tilda hangs when startup-command is not found

### ISSUE THREAD

**Issue by nifr** [lanoxx/tilda#144]
tilda hangs on start If i enter a non-existant "`Custom Commnand`" under "`Title and Command`" like

    mux start default
    # or with fallback
    mux start default || $SHELL

and set "`When Command exits`" to **Drop to default shell** as a fallback.

if `mux` is not installed (yet) I would expect tilda to open my default shell (zsh) after the `mux` command  has failed with exit code 1.

The behavior should be the same as when creating a file `/usr/local/bin/shell-session` with content ...

    #!/usr/bin/env sh
    mux start default || $SHELL

... and using that as the `Custom Command`.

Now if I enter the custom command directly - tilda hangs.
If I invoke the script as custom command - the fallback works.

Tested against `1.1.11`, `1.2.1` and the current `master` branch.

**Comment by lanoxx** [comment]
Fixed by 6bfcb0bfb3bd81616756f0803c72a4b0f78c34a9

**Comment by nifr** [comment]
Thanks :)
