### ISSUE TITLE
Can't input "accents" inside a tilda terminal 

### ISSUE THREAD

**Issue by rcalsaverini** [lanoxx/tilda#148]
Hi there,
I'm trying to configure tilda but there seems to be a problema where I can't use keys like `~`, or `´` inside the tilda terminal (so I can't, for instance, type `cd ~` or type letters with accents in a file while editing on vim). The key seems to be ignored, or maybe just the character is not inputted.  Those keys work perfectly in other terminal applications. 

My keyboard have a ABNT2 brazilian keyboard layout. Maybe this is the problem?

**Comment by pik** [comment]
Do you have the same problem with Gnome-Terminal? Is it Tilda specific? This might be better resolved on the forums for your linux distribution/elsewhere but could provide these details: showkey --ascii for your ` and ~ keys. Also xmodmap output.

**Comment by rcalsaverini** [comment]
Sorry for the delay in answering, but I was away from my work computer.

It seems to be intermittent. It only happened on tilda, but since it's intermittent I can't be sure that I was just lucky that it didn't happened on other terminals. I'm thinking it's probably not a tilda problem.

Thanks for your help.

**Comment by rcalsaverini** [comment]
Update: 
I seem to have been able to reproduce it consistently and it seems related to tmux. In the preferences section of tilda I changed the default command to "tmux". When I start tilda with this configuration, the keys won't work. If I start tilda with the default shell (zsh in my case) and only call tmux inside this new shell, it seems to work normally.

**Comment by lanoxx** [comment]
I am not quite sure what shell you get wrapped around tmux when you start it like this. Its quite possible that you get dash or something else instead of bash. If you want to be sure, you can try to start it like this:

    /bin/bash -c tmux

**Comment by lanoxx** [comment]
Closing. Please reopen if you experience this problem again.
