### ISSUE TITLE
tab font

### ISSUE THREAD

**Issue by bqion** [lanoxx/tilda#149]
Hello

I've searched but didn't found a possibility to change the tab fonts.
Maybe I've missed it?
If not, that would be a great feature. 

Cheers
bqion

**Comment by lanoxx** [comment]
Did you try to change the CSS for the tab font?

**Comment by bqion** [comment]
Found the solution: 
$HOME/.config/gtk-3.0/settings.ini

add the following line with your preferred font e.g.:
gtk-font-name=DejaVu Sans Mono 8

btw: great work! 
using tilda with i3wm
