### ISSUE TITLE
Tilda fullscreen not working

### ISSUE THREAD

**Issue by TildaUser** [lanoxx/tilda#151]
This has recently broken for me. I launch tilda and fullscreen works...then after toggling once or twice, it no longer works (tilda put into a window). 

Running arch with the awesome wm.

Any ideas?

**Comment by andrewlin16** [comment]
Can confirm I am getting this issue too. Fullscreen does not stick after the second toggle. Furthermore, pressing the fullscreen key does not make tilda fullscreen until the second press.

Using Arch Linux with Openbox.

**Comment by richardpearl** [comment]
Getting this issue too. Also Arch with Openbox.

**Comment by pik** [comment]
I'm using Arch w/ Openbox and don't have this issue? Can you guys add some package build details.

**Comment by andrewlin16** [comment]
Not sure what details you need. Openbox is version 3.6-1. Tilda is from tilda-git on AUR, version 5a6c3df-1, though I can confirm I still get the issue on Arch's version of tilda.

**Comment by pik** [comment]
Nevermind, I was in fact able to reproduce the same bug - it actually took
me 3 toggles though.

**Comment by lanoxx** [comment]
Does this bug only occur when using Openbox?

**Comment by TildaUser** [comment]
@lanoxx 

No, I get it in awesome too.

**Comment by TildaUser** [comment]
I reverted back to gtk3-3.16.2, so it works again.

**Comment by lanoxx** [comment]
Looks to me like some issue with gtk then. Tilda really just calls `gtk_window_fullscreen` and thats all. Maybe its worth to report a bug against GTK?

**Comment by pik** [comment]
Yes, it looks to be a gtk problem - this might be useful for debugging it: https://github.com/pik/tilda/commit/a938e8bbc51b836f7562dc136e44688b42fdfa3f 

I keep planning to myself :S

**Comment by newsgrep** [comment]
I use tilda 1.2.4 together with libgtk3 3.16.6.1 und i3wm 4.10.3. I do the following:
0. open tilda --> I can see it but it is not fullscreen
1. and switch it to fullscreen mode --> it turns fullscreen
2. hide it by useing the hotkey --> tilda hides
3. press tilda hotkey again --> it returns fullscreen
4. hide it again by useing the hotkey --> tilda hides
5. press tilda hotkey to return it like in 3. --> tilda returns not fullscreen
6. when I switch to fullscreen mode again --> nothing happens

if I would try to turn to fullscreen mode once more the cycle would repeat.
So it is not returned to fullscreen after hiding twice.

**Comment by lanoxx** [comment]
If I am not mistaken then Tilda was only affected by this on Gtk 3.16, I have recently pushed a fix that changes this for users of GTK 3.16, so closing this. If its still an issue feel free to reopen.
