### ISSUE TITLE
Tilda re-opens too small

### ISSUE THREAD

**Issue by gazhay** [lanoxx/tilda#153]
From time-to-time when tilda is hidden by keybinding or auto-hide, trying to show it again results in a 1line high window with no output. 

Today (during ubuntu upgrade) this happened and when i right-clicked and tried to open preferences it crashed, killing the update.

I'm attempting to recover the upgrade, and having had the issue in the past, you may conclude i was a fool to do an upgrade with tilda, but thats where we are.

**Comment by lanoxx** [comment]
Hi,

from which version to which version did you upgrade? Recovering a broken upgrade on Ubuntu should not be too hard. I have done that a few times without to much issues.

I personally have not had the problem recently, I suggest you check if you can still reproduce it with the new version. If you were upgrading from an older Ubuntu then you might still have had a 0.9.x version of tilda which is very old and has different bugs. If you know how to compile source code, then I recommend to build the latest 1.2.x version by yourself, it has more features and a few additional bug fixes that are not in tilda 1.1.x. The latest git master should also be stable enough to use on a daily basis.

**Comment by gazhay** [comment]
I have built from git and will report back if issue persists.

I recovered the upgrade after much purging and reinstalling.

**Comment by gazhay** [comment]
Hi,

Just bought a new machine today - fresh 15.04 install - bug is back.
Can start tilda, open it once, then stays shrunk.

just FYI

**Comment by lanoxx** [comment]
On Ubuntu 14.04 with the latest Tilda compiled from git I cannot reproduce the issue. If you still have this problem, please reopen and provide more information and maybe a screenshot.
