### ISSUE TITLE
Tilda Mac OS X compatibility? 

### ISSUE THREAD

**Issue by pik** [lanoxx/tilda#156]
Wondering if this has ever been pursued and if there are any strong reasons that would prevent Tilda from playing nice with OS X with some updates to the build (esp. very doubtful that the keybinding code would remain compatible, or how hard it would be to substitute).

**Comment by lanoxx** [comment]
I do not have a Mac, so there is no way I can test on Mac or support it. If someone comes around who want to volunteer for this than I am happy to accept patches. I am going to close this but if anyone wants to step up and provide patches, we can still reopen it.
