### ISSUE TITLE
Increasing Window scale to 100% when offset is set does not behave correctly 

### ISSUE THREAD

**Issue by pik** [lanoxx/tilda#157]
Steps to reproduce: 
Set window at a displaced position, set width or height to 100% (respectively). Toggle fullscreen on and off -- now the window shows up at the set width or height but displaced to the originally set position (with a portion of it no longer on the screen).

**Comment by TildaUser** [comment]
This is probably related with the fullscreen issue too. I wonder if there was an update or something in GTK that messed this up.

**Comment by pik** [comment]
@TildaUser I'm looking into the fullscreen issue but that seems to be regression introduced after gtk 3.14 (downgrading appears to fix it) - where as this behaviour persists, so I opened a separate issue for it.

**Comment by lanoxx** [comment]
Maybe it would make sense to deduct the `x_offset` from `max_width` and the `y_offset` from the `max_height`?

**Comment by pik** [comment]
After updating to `gtk3 3.18.9-1` I can't seem to reproduce this (there is still a minor quirk about changing to 100% width/height with an offset will off-screen it but I wouldn't call that a bug), maybe it's good to close?

**Comment by lanoxx** [comment]
Ok closing this.
