### ISSUE TITLE
Tilda opens on wrong screen (based on mouse location or window focus)

### ISSUE THREAD

**Issue by ntrp** [lanoxx/tilda#16]
Tilda opens randomly on each monitor when pressing the shortcut. Usually it opens where the mouse or window focus is, eventually this behaviour doesn't occour and it keeps opening on one monitor for some time. I don't know yet the pattern of the bug...

Will try to investigate the sourcecode maybe I can help spotting the problem, in the meantime if you have any suggestion or test request let me know.

**Comment by lanoxx** [comment]
I pushed commit 18c4ffa14f46c7dd0648412917e835a9f0d6932f today, which might possibly fix this problem. Please report if you can still reproduce this issue.

**Comment by lanoxx** [comment]
@ntrp Ping

**Comment by ntrp** [comment]
Unfortunately I don't have a second monitor at the moment.. I will check as soon as got some time at work

**Comment by ntrp** [comment]
Sorry for the long delay, I finally got an external monitor and time to test. The issue seems resolved but I don't know if it is related directly to the commit or to the fact that I updated the system regularly.. anyway now it works as excepted, I can select the monitor from the options and it instantly switches to that monitor.

**Comment by lanoxx** [comment]
Ok. Thanks for reporting back. Im glad its fixed for you.
