### ISSUE TITLE
Dealing with deprecated config settings? 

### ISSUE THREAD

**Issue by pik** [lanoxx/tilda#161]
Just to centralize this discussion in one place. Some ideas are:
 
* leave unused options with a deprecation warning. 
* Add a flag compile(or)runtime to not error on unused config values. 
* Add a parser to convert and/or prune old-config opts.

**Comment by pik** [comment]
So if there aren't any better ideas I think I will add a CFG_DEPRECATED option to lib-confuse because there really should be a neat way of doing this and I would like to have it resolved for the lib-vte upgrade option. Libconfuse does offer some callbacks but from what I understand  those aren't flexible enough to fit our needs. I don't know if I'll be able to get a patched pulled into libconfuse - but the library is small enough to bundle our own copy with Tilda if need be. imho this may be preferable to writing our own config-parser or switching to another library entirely. @lanoxx  thoughts?

**Comment by lanoxx** [comment]
You can try to contact the developers on github, but I actually do not have much hope. The project looks dead to me, there are already several pull requests that have not been resolved and the last commit is more that a year ago if i remember correctly.

**Comment by pik** [comment]
Is there another relatively small config library that you would be happy moving to otherwise?

**Comment by lanoxx** [comment]
Another thing: If we depend on a newer libconfuse version than whats in most distros, then users will not be able to build from git on stable releases unless they also build libconfuse first.

**Comment by pik** [comment]
Would there be any issue with bundling our own libconfuse version?

**Comment by lanoxx** [comment]
I have been thinking about libconfig. But I have never used it so far.

**Comment by lanoxx** [comment]
I can imagine that if we ship our own libconfuse version, then distributions might complain and ask us to depend on the version in their distribution?

**Comment by lanoxx** [comment]
I opened an issue in libconfuse: https://github.com/martinh/libconfuse/issues/24

Feel free to add a comment if my explanation of your suggested CFG_DEPRECATED option is not what you had in mind.

**Comment by lanoxx** [comment]
This could also be interesting for us:
https://github.com/martinh/libconfuse/pull/

I don't like the solution with using `__unknown` though

**Comment by pik** [comment]
> I opened an issue in libconfuse: martinh/libconfuse#24
  Great, thank you for this. 

>  then distributions might complain and ask us to depend on the version in their distribution?

We can just install with a different name/namespace, I'm not sure why this would bother them - but I don't really know? 

> This could also be interesting for us:
https://github.com/martinh/libconfuse/pull/

I haven't tried it but it seems like `__unknown` would work for us - although I would prefer to specify what is deprecated explicitly and give a handling action (comment out or prune from file) something along the lines of: 
```
CFG_BOOL("use_image", FALSE, CFGF_DEPRECATE & CFGF_DROP)
```
Also if we are going to patch libconfuse we should consider dealing with #110 as well, since distinguishing between fields set-to-empty and fields entirely absent from the config file is properly something the library should handle. 

Looking at it - I'm not really a fan of their code structure, instead of providing some convenience methods to handle parsing config, they provide basically a one-shot solution which is inflexible and changes to its functionality have to go directly into the library.

**Comment by lanoxx** [comment]
I think we can close this bug. Your solution of removing deprecated config values that you wrote for the vte port works quite well and is an adequate fix for this issue. Updating `libconfuse` would probably be the preferred way but there has been no response from upstream so I pretty much think the developer gave up on the library. Anyway if `libconfuse` really gets resurrected and someone writes an update then we should open a separate bug that deals with upgrading to a new `libconfuse` version and then we also need to consider a backwards compatibility.

Feel free to reopen if you disagree.
