### ISSUE TITLE
Keybindings page is getting too large

### ISSUE THREAD

**Issue by pik** [lanoxx/tilda#163]
I think it may be a good idea to switch to a notebook-column style binding list; both gnome-terminal and guake do this and it looks better imho.

**Comment by lanoxx** [comment]
Yes, thats something that I think we should do at some point, but its not a priority for me at the moment. If you want to work on it you are welcome to do so.

**Comment by x2b** [comment]
I modified this a while ago in my own branch: https://github.com/x2b/tilda
Does that look suitable to you?

**Comment by pik** [comment]
+1 looks better to me, especially as we add more hot-keys.

**Comment by lanoxx** [comment]
I will take a look at the code this week end and possibly merge it.

**Comment by lanoxx** [comment]
It looks like you made a lot of changes to the tilda.ui file so I cannot merge that code without a lot of work. Please separate the keybinding ui changes from the other changes in the ui file and rebase it onto master.

**Comment by lanoxx** [comment]
I had a look at gnome terminal which has a similar solution, but they additionally use sections that can be collapsed. Adding a screenshot from Gnome Terminal for reference:

![selection_017](https://cloud.githubusercontent.com/assets/691311/8633929/fb8a65d6-27e3-11e5-8efe-3432ffb26dac.png)

**Comment by x2b** [comment]
@lanoxx It would be nice if GTK would just ship a suitable widget instead of people having to reinvent the wheel all the time...

Anyways, this is derived from your master branch and should be easy to merge: https://github.com/x2b/tilda/tree/dialog

**Comment by x2b** [comment]
@lanoxx could yo ugive me some feedback?!

**Comment by lanoxx** [comment]
Hi,

I did not have time to review yet. I will take a closer look this week and let you know. Based on a quick look that I just had the patch looks quite huge so I need so some mor time to review it.

**Comment by x2b** [comment]
No offense^^ but it also took quite some time to make as well, I would be happy if the code makes it into tilda at some point...

**Comment by lanoxx** [comment]
No offense taken. I actually would like to see this feature in tilda, but it must come with a clean commit. 

Now about the review, I just had a look at your branch, the problem with this branch is that I cannot just merge the "Modified settings dialog" commit into tilda, I must take your whole branch including all other commits. I don't want to do that. What I would like to see is one or several commits that implement *only one feature* (keybinding changes) and that applies cleanly to my master branch.

Right now, when I try to merge your dialog branch I also get the following commits:

 * Multi-Monitor support: Use monitor names
 * Pull up the window before showing the wizard
 * Fixes lanoxx/tilda #32
 * Attempt at fixing lanoxx/tilda#97
 * A first try to fix lanoxx/tilda#131
 * tilda window reacts to changes in screen geometry

If I try to cherry-pick the "Modified settings dialog" commit into my master branch, then I get a long list of merge conflicts and I don't have the time to review all of them.

**Comment by x2b** [comment]
Well, ok... I don't seem to be getting it... I am talking about the dialog branch of my repository:

https://github.com/x2b/tilda/tree/dialog

This branch is one commit away from your commit here:

https://github.com/x2b/tilda/commit/40930a5619bbbeb8aef61a206fb13d8cb8b27c11

My commit was two days after yours, I used your latest commit as a starting point...

**Comment by lanoxx** [comment]
What you see there is one merge commit, but that merge pulls in several other commits:

The following screenshot is taken from `gitk` directly after the merge of your dialog branch:

![selection_025](https://cloud.githubusercontent.com/assets/691311/9028175/e5cf7b80-396f-11e5-9d69-ee09ec2f331c.png)

As you can see there are several merge commits plus the commits I have listed above. On github or in `git log` you will only see the topmost merge commit but that does not mean there is only one commit.

What you probably did was to merge your master branch onto my master, but that won't work. What you probably need to do is to use `git cherry-pick` on the *Modified settings dialog* commit. So that you cherry-pick only that commit onto a branch that is equal to my current master. Then it will be easy for me to review just that commit and merge it. If you need some help with cherry-picking and rebaseing I can recommend this link to you: http://think-like-a-git.net/

**Comment by pik** [comment]
@x2b any plans for this?

**Comment by x2b** [comment]
Well, I might take another whack at this, just please provide me a sha to start from

**Comment by lanoxx** [comment]
Hi, thanks for your reply, please start at the latest commit in git master, which at the moment is: d775f8db8ea61cc9aa2c6d7fb7bbdf67f7df61d4

Here is some more advice to make it easier for me to merge this in the future:

1. Make sure your pull request has only commits for one feature, for example if you touch both the 'Appearance' and the 'Keybindings' tab, then put each change into a separate pull request.
2. Make small, clean commits that are easy to review and which form a consistent set of changes.
3. If you make code formatting changes, white space changes or other fixes in places unrelated to this feature, then please submit them in a separate pull request.
4. In the commit message: Put a clear description what the commit does (not: "attempt at fixing issue #foo", but for example: "wizard.c: Implement logic for storing hotkeys in a GtkTreeModel"). Also try to name the file where most of the changes are in the front of the commit name. You can still put a note about which issue your fixes into the next line.
5. If you touch the tilda.ui file with glade, please pay additional attention, if glade tries to clean up or reorder the contents of the file and if it does use `git add --patch` to only commit the relevant parts of your change. This happens often when you use a different version of glade then what was last used to edit the ui file. Or alternatively make one commit which only contains the formatting and clean up changes introduced by your glade version and then another commit where you commit the actual changes made by you.
