### ISSUE TITLE
How to type tilde without activating Tilda?

### ISSUE THREAD

**Issue by sabrehagen** [lanoxx/tilda#165]
I've tried searching the issues, but haven't come up with anything so I hope this isn't a re-ask of this question. If we bind Tilda to the tilde/grave key, how do we then type tilde? Is there a workaround?

**Comment by lanoxx** [comment]
No, thats not possible. But you can try to press the alt key and type u followed the Unicode number for the tilde key. If that does not work you need to google if there is another way to enter characters based on their ascii or unicode number. Anyway whatever you choose as a Key, I recommend you to combine it with a modifier such as alt, ctrl or super.

**Comment by sabrehagen** [comment]
Appreciate your help, thanks.
