### ISSUE TITLE
Moving a tab breaks copy and paste hotkeys 

### ISSUE THREAD

**Issue by pik** [lanoxx/tilda#167]
Reorganizing the tabs by dragging them into a different position breaks the copy & paste hotkeys. 

edit: 

So the reason this happens is because Tilda is relying on the notebook_page # matching the tilda_terminal #, which is an invalid assumption, since moving the tabs re-orders the notebook pages. The easy solution would probably be to store an array of pointers to existent pages, the nicer solution would be to use `tt` instead of `tw` in the relevant call-backs. 

Doing the later I think would involve listening to `key-press-event` on the terminal instead of using `gtk_accel_map_add_entry`. I'm not sure it's nice to split up keybinds -- but this is kind of already done in  `key_press_cb` for `GDK_KEY_Menu`; so `ccopy` and `cpaste` could be triggered in there rather than tilda_window.

**Comment by lanoxx** [comment]
This was broken by commit a28a512834aa4e741559305e02149549159e709a in which I tried to fix the copy/paste hotkeys when the scrollbar is on the left. I am thinking if I just revert that commit until I have time to write a proper fix.

**Comment by pik** [comment]
@lanoxx I added a quick-fix, it's not very nice though. imho if copy or paste (and search as well actually) only need the current terminal and not the window it would be preferable to pass it directly or to give them a straight-forward method of access.

**Comment by lanoxx** [comment]
@pik I agree that would be the preferred method, but I still merged it for now so that the bug is fixed.
