### ISSUE TITLE
Unity launcher disappears when running in fullscreen mode

### ISSUE THREAD

**Issue by sryze** [lanoxx/tilda#171]
When running tilda in fullscreen mode and with a transparent background, you can observe that the Unity launcher and the menu panel on top disappear from the screen.

**Comment by lanoxx** [comment]
Please provide more information, in what why is this a problem, does it come back when you hide tilda? Does it stay hidden? Which tilda version are you using?

**Comment by lanoxx** [comment]
Closing, this. I need more information and maybe a screen shot. Please reopen if you can provide more information.

**Comment by sryze** [comment]
Sorry for not responding for such a long time, I haven't been using Linux much for a while. 

Below are the screenshots of a maximized browser window and what it looks like with and without fullscreen tilda on top:

![tilda-unity](https://cloud.githubusercontent.com/assets/4525736/11606828/ebb33cd8-9b50-11e5-89d2-246b6a0941b7.png)
![tilda-unity-hidden](https://cloud.githubusercontent.com/assets/4525736/11606829/ed30b4fa-9b50-11e5-986f-f506dffa1ee3.png)

As you can see, the top panel and launcher are not visible with tilda open. Also, I think I've the exactly same thing happening with gnome-shell.

It's not like I can't live with this, in fact I've recently enabled auto-hide in Unity so it's not much of an issue any more, just thought you might want to look into it.

**Comment by sryze** [comment]
Still seeing this on Ubuntu 16.10.
