### ISSUE TITLE
wrong tab title after moving tabs

### ISSUE THREAD

**Issue by atommixz** [lanoxx/tilda#173]
you can run app that rename tab, like 'weechat' and try moving tabs. After that, weechat tab title setting on another tab

**Comment by lanoxx** [comment]
Which version of tilda do you use?

**Comment by atommixz** [comment]
git, yesterday update from this repo

**Comment by atommixz** [comment]
http://rghost.net/92sYyhJ52.view
http://rghost.net/8ZX7yNc5s.view

**Comment by lanoxx** [comment]
I still don't really understand what is the problem, can you explain a little more detailed what you are doing and what is going wrong?

**Comment by atommixz** [comment]
- I open 4 tabs
- on 3rd I run weechat
- move weechat tab to the left on one position
- what I see:
http://rghost.net/8fY28Djd7.view
http://rghost.net/7rWJh6Cty.view

**Comment by lanoxx** [comment]
I have pushed two commits which should hopefully fix this issue. Please let me know if you can still reproduce the problem.

**Comment by atommixz** [comment]
Works for me now. Thank you very much

**Comment by lanoxx** [comment]
You are welcome
