### ISSUE TITLE
Tilda not closing using any keybinding on Lubuntu 15.04

### ISSUE THREAD

**Issue by MauJFernandez** [lanoxx/tilda#181]
I just installed Lubuntu 15.04 on my netbook and when setting my usual keybindings I discovered that pulling up the terminal is not working, but pulling it down it does, so the only way to make it disappear is to exit the application.

**Comment by lanoxx** [comment]
It this still an issue? Ubuntu 15.04 seems to have tilda 1.2.2 but the latest is 1.2.4, also did you try to build the lastest master?

**Comment by hcoosthuizen** [comment]
I was experiencing this issue on Ubuntu 15.04 with version 1.2.2-1 of Tilda.  Built and installed 1.2.4 and the issue seems to be resolved.

**Comment by lanoxx** [comment]
Great, I will close this then.
