### ISSUE TITLE
[feature]  mouse quick  copy-paste

### ISSUE THREAD

**Issue by cj1324** [lanoxx/tilda#185]
feature

mouse selection-changed event  -> copy
mouse right-click -> paste

but popup_menu ...

patch code
https://gist.github.com/cj1324/7af3d4b80d7221fd0778#file-gistfile1-txt

This feature requires improvement and merge

**Comment by lanoxx** [comment]
Did you try:

1. mark some text with the mouse
2. use middle mouse button?

Thats a common feature of the XServer and should paste the selected text.
