### ISSUE TITLE
Support vertical bar cursor

### ISSUE THREAD

**Issue by sschaef** [lanoxx/tilda#191]
I'm a user of [neovim](https://github.com/neovim/neovim), which supports vertical bar cursors out of the box in a terminal. However, tilda doesn't seem to support them too. It always shows the block cursor.

I was told that `printf '\e[5 q'` should change the cursor shape and `printf '\e[1 q'` should restore it. Both commands do not seem to have any effect. I was also told that vte3 would support such a cursor shape, tilda right now still uses vte2.9.

Maybe such a vertical bar cursor can be supported by upgrading to the newest vte version, maybe there is another way. At least it would be nice if tilda could show such a cursor shape.

**Comment by lanoxx** [comment]
Support for setting the cursor mode was recently added (options are Block, IBeam and Underline), if you compile from the master branch you can already use it, otherwise you will need to wait for version 1.3

**Comment by sschaef** [comment]
Cool, nice to hear that. I tried it out and while the new cursors work I see still two problems:

- Programs can't change which cursor shape is displayed, it entirely depends on the user configuration.
- The cursor color is now always white for me, whereas in a previous version it was possible to override the color, which is done both by zsh and vim.

**Comment by lanoxx** [comment]
Ok, reopening, we probably need to do something to handle those command sequences.
