### ISSUE TITLE
tilda-git version

### ISSUE THREAD

**Issue by JonnyMako** [lanoxx/tilda#193]
I'm installing tilda-git via aur in Arch Linux. And the system prompts me to keep updating to the latest version. When I update, the new version still uses the old version number so the next time I check for updates, tilda-git is again "updated" ad infinitum.

==> Software upgrade (new version) :
aur/tilda-git d775f8d-1 -> 5a6496c-1

Also, when I do tilda --version, I get:

** (process:29303): WARNING **: Warning: show_on_monitor_number is no longer a valid config option for the current version of Tilda.

**Comment by lanoxx** [comment]
Hi,

regarding the update I am not sure this is an issue of tilda or of the packaging. It sounds more like there is a problem in the AUR package, please check with the package maintainer first.

Regarding the above warning. I deprecated the "show_on_monitor_number" option yesterday and replaced it with "show_on_monitor" which now stores the name of the monitor where tilda is shown. This warning should only appear once and not when you start tilda the second time.

**Comment by JonnyMako** [comment]
Thanks, notified package maintainer on Arch.

**Comment by lanoxx** [comment]
So I think this is not a bug in tilda, please reopen if I am wrong.
