### ISSUE TITLE
Tilda sometimes doesn't restore (v1.2.2)

### ISSUE THREAD

**Issue by tenleftfingers** [lanoxx/tilda#195]
I'm running 1.2.2 on Ubuntu 14.04 and F1 generally hides/restores tilda the first few times. Eventually, it will not restore from it's hidden position (although "Tilda" appears in the global menu and disappears if I press F1 again so it's partially working).

I'm happy to provide further info or try other versions if deb packages are available.

**Comment by ddulic** [comment]
Having the same problem on Arch Linux, Gnome 18.1

**Comment by lanoxx** [comment]
@ddulic Are you also using 1.2.2? Have you tried using 1.2.4?

Please give some more information. Also if possible, try to compile the latest version from git master and let me know if that fixes the problem.

**Comment by lanoxx** [comment]
Also please let me know if you have the pulldown animation enabled.

**Comment by tenleftfingers** [comment]
OP here. I have the animation enabled. I can try without for a while and see if it changes anything. I'll report back. Thank you.

**Comment by lanoxx** [comment]
The thing with animation is that it resizes the tilda window which seems to break a lot of things. I have changed it a few weeks ago to just move it and not resize it. Additionally tilda now sets some EWMH hints to avoid some additional problems with some window managers. If disabling animations fixes the issue for you, then I recommend you to leave them off or switch to the latest version in git.

**Comment by ddulic** [comment]
Using 1.2.4. with animation enabled. Haven't had the error for a few days and now I didn't change anything. I think the problem occurs when you press the keybind too much.

**Comment by tenleftfingers** [comment]
I'm using the version I reported the issue with but with animation
disabled. No problems since then.

**Comment by lanoxx** [comment]
Thanks for reporting back. Unfortunately I think the patch that fixed the animation behaviour is too large to backport for a stable release do ai recommend to disable animation until I have released 1.3. I am going to close this bug. Please reopen if you can reproduce this issue without animations enabled.
