### ISSUE TITLE
Emacs status bar and text disappear

### ISSUE THREAD

**Issue by arvindkhadri** [lanoxx/tilda#197]
Status bar and text inside emacs become invisible and repaint themselves on a key press or action in the area. I am using tilda v1.2.4 on Arch Linux. This issue is not reproducible with gnome-terminal.

**Comment by arvindkhadri** [comment]
Screenshot before hiding terminal
![screenshot from 2015-10-23 16-43-39](https://cloud.githubusercontent.com/assets/606431/10691221/36df507a-79a5-11e5-98b3-b570af1d4e11.png)

Screenshot after hiding and showing terminal
![screenshot from 2015-10-23 16-47-01](https://cloud.githubusercontent.com/assets/606431/10691239/5887469c-79a5-11e5-9ca5-1f798ccb363c.png)

**Comment by lanoxx** [comment]
Do you have the hide animation enabled?

**Comment by arvindkhadri** [comment]
Yes, pulldown animation is enabled in the Extras under Appearance.

**Comment by lanoxx** [comment]
This is a known issue that has already been fixed in the next version. Until its released you can either try to build from git master or disable the animation as a work around.

**Comment by arvindkhadri** [comment]
I see. Thanks. 
-------
P.S:great project.
