### ISSUE TITLE
Tilda couldn't bind to F* keys

### ISSUE THREAD

**Issue by ruXlab** [lanoxx/tilda#200]
Hello

I want to use F1 to open tilda but after upgrade to 14.04 it wouldn't bind to any F* keys. I constantly getting error ```The keybinding you chose for "Pull Down Terminal" is invalid. Please choose another.```

Before I thought somehow gnome or unity interfere with F1 but tried to bind it to virtual F20 (which doesnt exists on keyboard obliviously) using xdotool and got the same error  

Current OS: Ubuntu 15.10 x32
Tilda: 1.2.4-1

/* *and yeah thanks for your work* */

**Comment by lanoxx** [comment]
Any chance you could try the latest version from master to see if that helps?

**Comment by ruXlab** [comment]
Hello
I've tried to build it but no luck - something went wrong during compilation. Might be because it was in the docker container. I'm not good at these things

Anyway, I've just installed verson 1.3.0 from https://launchpad.net/ubuntu/+source/tilda built on 2015-11-19 and got same issue

![screenshot from 2015-12-12 20-15-49](https://cloud.githubusercontent.com/assets/1110234/11763729/7fc4eee6-a10d-11e5-8dd0-68b622ff7fc7.png)

**Comment by ruXlab** [comment]
After fresh reinstall ubuntu 15.10 issue has gone. Upgrade to 16.04 didn't break things as well

Issue can be closed, thanks
