### ISSUE TITLE
Default to 2.91 and make a release

### ISSUE THREAD

**Issue by egmontkob** [lanoxx/tilda#202]
Vte library version 2.90 is no longer maintained. 2.91 is the actively developed one, already including important fixes (e.g. the security/privacy issue that the scrollback buffer is no longer stored on the disk as plain text).

The configure script should default to the new one if it finds it, and a tarball should be released so that distros (e.g. forthcoming Ubuntu Xenial LTS) automatically and quickly pick up the change.

**Comment by lanoxx** [comment]
I will definitely do it this week, since Debian put a deadline on the package until 24.11.

**Comment by egmontkob** [comment]
Awesome, thanks! :)
