### ISSUE TITLE
Readme image contains depricated feature.

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [lanoxx/tilda#204]
https://github.com/lanoxx/tilda/blob/master/images/tilda_appearance.png

It still has an image of the feature I dearly miss now that 1.3 has arrived.

that's um... it's maybe coming back at some time... maybe?

lanoxx plz.

(;´༎ຶД༎ຶ`) (i know this isn't your fault...)

**Comment by lanoxx** [comment]
Do you mean the background. I don't think thats coming back since it was removed from libvte.

**Comment by Ghoughpteighbteau** [comment]
yah. It was removed in libvte in 2013. I had forgotten about that, and tilda 1.3 hit live in arch just now. 

Might want to update though (and add some notes to the change log!), cause I was confused as to what was going on for a couple of hours :(

**Comment by lanoxx** [comment]
Fixed. Thanks for the reminder.
