### ISSUE TITLE
Cannot be transparent under Gnome 3.18

### ISSUE THREAD

**Issue by IvoMajic** [lanoxx/tilda#212]
I believe the issue that tilda had with GNOME 3.10 (https://github.com/lanoxx/tilda/issues/29) and that was fixed (worked for me in 3.16) is back in 3.18. Now when I turn on transparency, only two gray dots appear on each side of the terminal. I am using Arch Linux.

Here is a screenshot with transparency ON (notice the two dots in the left and right top corner):

![screenshot from 2015-12-25 08-50-22](https://cloud.githubusercontent.com/assets/1269362/12001230/b0bae524-aae4-11e5-9b5c-5b87c1e223ba.png)

**Comment by Taleuntum** [comment]
I too have this issue, but you can make tilda transparent with transset-df and devilspie.

**Comment by IvoMajic** [comment]
Installed the new 1.3.1 version, and it is working now!
