### ISSUE TITLE
Copy paste shortcut not working in Tilda 1.1 series

### ISSUE THREAD

**Issue by spharish** [lanoxx/tilda#213]
Other key bindings like quitting the window, opening new tab, etc are all working, but copy and paste keybinds(Ctrl+Shift+C, Ctrl+Shift+V) are not workig

**Comment by tojamrok** [comment]
That happens for me on Xubuntu with Xfce.  Regardless of the shortcut I choose, there is following info:

(tilda:16985): GLib-GObject-WARNING **: invalid cast from 'GtkScrollbar' to 'VteTerminal'

(tilda:16985): Vte-2.90-CRITICAL **: vte_terminal_copy_clipboard: assertion 'VTE_IS_TERMINAL(terminal)' failed

**Comment by lanoxx** [comment]
@spharish, @tojamrok: Which version of tilda are you using.

**Comment by tojamrok** [comment]
It's 1.1.11.

**Comment by lanoxx** [comment]
Thats pretty old. This bug is fixed in 1.2.4 and 1.3.1 I recommend you to update. Which distribution are you using?

**Comment by spharish** [comment]
I also use version 1.1.11 which is available in the Ubuntu Software Center. Is it possible for you to update the version in the Ubuntu Software Center, as directly downloading the latest version from github is causing many dependency issues?

**Comment by lanoxx** [comment]
I can probably backport the fix from 1.2 to 1.1, but you should be aware of one thing: There is already tilda 1.1.13 and Ubuntu is still at 1.1.11 and there has been no attempt to pull the new version so far. So even if I make a new 1.1.14 release that fixes this bug in the 1.1 series, I am not sure that it will ever make it into Ubuntu 14.04. :(

**Comment by lanoxx** [comment]
Alternatively you can try to build version 1.2.4 that should not cause dependency issues on Ubuntu 14.04.
