### ISSUE TITLE
Tilda preferences window does not apply gtk theme properly

### ISSUE THREAD

**Issue by JonnyMako** [lanoxx/tilda#217]
I'm using the FlatStudio Dark theme:
http://gnome-look.org/content/show.php/FlatStudio?content=154296
And I don't see the color palette in the Tilda preferences window
![tildanocolorpalette](https://cloud.githubusercontent.com/assets/6559121/12375642/84698f20-bc91-11e5-9000-4d235b829c4b.png)

**Comment by lanoxx** [comment]
I am currently not sure whats the reason for this. Are you sure its not an issue with the theme?

**Comment by JonnyMako** [comment]
Its possible its is an issue with the theme. If you let me know what UI elements are being used for the palette, I can test with some other applications with similar elements. If it turns out to be a theme issue, I'll close this one.

**Comment by lanoxx** [comment]
It uses GtkColorButtons, I think you can try the gtk3-demo application it should have GtkColorButtons somewhere. If it works there then its maybe a problem of tilda. If not then its a theme issue.

Btw. tilda can load a custom style.css file in which you can override your themes style, maybe that would work as a workaround a fix can be found. See the wiki for some details.

**Comment by JonnyMako** [comment]
Thanks for the reply. gkt3-demo has the same issue with "Pickers". I'll inform the theme maintainer.
