### ISSUE TITLE
Openning Screen minimizes tilda in Ubuntu 15.10 (tilda 1.2.4)

### ISSUE THREAD

**Issue by sdague** [lanoxx/tilda#230]
I have a really weird bug that I've narrowed down.

If you have a .bashrc that include something to modify the terminal name (i.e.)

```
    # if this terminal "is" an xterm (or compatible) build
    # a titlebar variable which is the same as the prompt more or less
    case $TERM in
        xterm*)
            TITLEBAR="\[\033]0;$MYUSER\h:\w\007\]"
            ;;
        *)
            TITLEBAR=""
            ;;
    esac
```

And you start tilda on Ubuntu 15.10. And then you run ''screen'', tilda minimizes. This isn't a normal tilda hide, it's actually an attempted Ubuntu Unity window minimization. The same things happens when you exit ''screen''. 

F1 brings tilda back, but this is really really weird that screen can trigger this behavior. Any ideas why? Is there something tilda could filter here to get rid of that?

**Comment by voidplayer** [comment]
Yes! im not crazy!

I reported this in #13 

I finally gave up if I dont misremember... but I no longer run the same programs nor it has ever happen again... but you might want to check that out too

**Comment by sdague** [comment]
As of Ubuntu 16.04 it seems to have fixed itself. I assume it's related to some underlying library.
