### ISSUE TITLE
ColorSelector

### ISSUE THREAD

**Issue by bretttjohnson1** [lanoxx/tilda#231]
Color selector only shows colors when highlighted. Shown in snapshot. Using kde dark theme.
![snapshot1](https://cloud.githubusercontent.com/assets/8139672/14320326/a091c574-fbe2-11e5-9093-d75d22c63a4e.png)

**Comment by lanoxx** [comment]
I am rather sure thats a theme issue. So closing for now. If you can reproduce this with GTK+'s default theme, then please reopen.
