### ISSUE TITLE
'always on top' doesn't work anymore in 16.04. 

### ISSUE THREAD

**Issue by dontaddcheese** [lanoxx/tilda#237]
Title says it all really. Tilda also doesn't get focus anymore when I move the mouse over it, I'm guessing these issues are related. It doesn't matter whether I install it from here or from official repo either.

**Comment by lanoxx** [comment]
Which window manager or compositor are you using?

**Comment by dontaddcheese** [comment]
Openbox, with or without compton, tilda will not stay on top.

**Comment by lanoxx** [comment]
Seems like an issue with Openbox to be. I cannot reproduce it with metacity. Can you try another window manager to see if it works there.

**Comment by dontaddcheese** [comment]
I've tried in xfce and the problem remains. There's also another thing 
I've notice since upgrading to 16.04, when tilda is active, it doesn't 
grab the mouse cursor like it used to. I have to press the key combo (to 
hide/unhide) to be able to type everytime, even if tilda is already 
unhidden. Before that it would grab the mouse whenever I moved over the 
window.

**Comment by dontaddcheese** [comment]
This was simply resolved by deleting old config files stored in ~/.config/tilda.
