### ISSUE TITLE
Search bar seems to have hard-coded background color

### ISSUE THREAD

**Issue by rogue-ronin** [lanoxx/tilda#240]
If I use a dark theme (try Xfce-dusk) I get a white background.

With some other dark themes, I get white-on-white text with invisible buttons.  I recognize that theming is a problem, and that this is partially related to the constant changes in gtk3 theming over the last few years.

I use dark themes because light themes blast me in the eyes. :)  Is there any chance to fix this?  

Honestly, though, I'd prefer if the search bar was more terminal-like instead of GUI-like. I get rid of all GUI elements in my usage of tilda.  (No title-bar, no scroll-bar, etc.)

Aloha!

**Comment by lanoxx** [comment]
I think I remember pushing something like that. At that time I probably did not have dark themes in mind. I think you can overwrite the default color using a custom stylesheet as a work around. When I have some more time I will fix this.

**Comment by rogue-ronin** [comment]
Thanks for responding.  I searched for an XML file, but couldn't locate one.  I presume it's therefore involved in the compile process somehow, which is beyond me.

Glad to wait.  Love tilda!

**Comment by lanoxx** [comment]
Take a look at the [wiki](https://github.com/lanoxx/tilda/wiki), in the section Border Issues its explained how to add a custom style.css, create that file and add some rule to style the background for example:

#search {
	background-color: #000;
}

If you are running are recent GTK+ version and you have enabled the `org.gtk.settings.debugger.enable-inspector-keybinding` option in the `dconf-editor`, then you can also use GTK Inspector to investigate the styling.

**Comment by rogue-ronin** [comment]
Oh, hey, thanks!  I'll investigate.

Aloha,

M

On Mon, Apr 25, 2016 at 11:05 PM, Sebastian Geiger <notifications@github.com
