### ISSUE TITLE
Tilda crashing on startup

### ISSUE THREAD

**Issue by rsvitale** [lanoxx/tilda#241]
Using arch linux, lxqt desktop environment, I get the following error log:

Process 3387 (tilda) of user 1000 dumped core.
                                                
 Stack trace of thread 3387:
#0  0x00007fd6a48b02a8 raise (libc.so.6)
#1  0x00007fd6a48b172a abort (libc.so.6)
#2  0x00007fd6a564db25 g_assertion_message (libglib-2.0.so.0)
#3  0x00007fd6a564dbba g_assertion_message_expr (libglib-2.0.so.0)
#4  0x00007fd6a53a07a7 n/a (libvte-2.91.so.0)
#5  0x00007fd6a53ba164 vte_terminal_set_colors (libvte-2.91.so.0)
#6  0x000000000040d143 n/a (tilda)
#7  0x000000000040de10 n/a (tilda)
#8  0x000000000040f00c n/a (tilda)
#9  0x0000000000409595 n/a (tilda)
#10 0x00007fd6a489d710 __libc_start_main (libc.so.6)
#11 0x0000000000409bc9 n/a (tilda)
                                                
Stack trace of thread 3390:
#0  0x00007fd6a49607f9 syscall (libc.so.6)
#1  0x00007fd6a566cafa g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007fd6a55fc929 n/a (libglib-2.0.so.0)
#3  0x00007fd6a564f2e6 n/a (libglib-2.0.so.0)
#4  0x00007fd6a564e975 n/a (libglib-2.0.so.0)
#5  0x00007fd6a4c25424 start_thread (libpthread.so.0)
#6  0x00007fd6a4964cbd __clone (libc.so.6)
                                                
Stack trace of thread 3389:
#0  0x00007fd6a495bc3d poll (libc.so.6)
#1  0x00007fd6a56280fc n/a (libglib-2.0.so.0)
#2  0x00007fd6a562820c g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007fd6a5628249 n/a (libglib-2.0.so.0)
#4  0x00007fd6a564e975 n/a (libglib-2.0.so.0)
#5  0x00007fd6a4c25424 start_thread (libpthread.so.0)
#6  0x00007fd6a4964cbd __clone (libc.so.6)
                                                
Stack trace of thread 3391:
#0  0x00007fd6a49607f9 syscall (libc.so.6)
#1  0x00007fd6a566cafa g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007fd6a55fc929 n/a (libglib-2.0.so.0)
#3  0x00007fd6a564f2e6 n/a (libglib-2.0.so.0)
#4  0x00007fd6a564e975 n/a (libglib-2.0.so.0)
#5  0x00007fd6a4c25424 start_thread (libpthread.so.0)
#6  0x00007fd6a4964cbd __clone (libc.so.6)
                                                
Stack trace of thread 3392:
#0  0x00007fd6a495bc3d poll (libc.so.6)
#1  0x00007fd6a56280fc n/a (libglib-2.0.so.0)
#2  0x00007fd6a5628482 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007fd6a5c246d6 n/a (libgio-2.0.so.0)
#4  0x00007fd6a564e975 n/a (libglib-2.0.so.0)
#5  0x00007fd6a4c25424 start_thread (libpthread.so.0)
#6  0x00007fd6a4964cbd __clone (libc.so.6)

**Comment by lanoxx** [comment]
Which version are you using?

**Comment by rsvitale** [comment]
I'm using 1.3.2-1

**Comment by rsvitale** [comment]
I tried opening tilda in xterm and an emacs shell and in both cases saw the following error:

Vte:ERROR:vte.cc:2599:bool VteTerminalPrivate::set_background_alpha(double): assertion failed: (alpha >= 0. && alpha <=1.) Aborted (core dumped)

**Comment by lanoxx** [comment]
I just pushed a commit that should fix this. Can you try with tilda 1.3.4 or the current master?

**Comment by rsvitale** [comment]
I tried with 1.3.4 and the master and received the same error.

**Comment by rsvitale** [comment]
I just updated tilda on a different computer (which is setup almost the same as the computer where I'm having trouble) and there are no issues...I'll see if I can find what's different/causing an issue.

**Comment by lanoxx** [comment]
There seems to be a problem with the background color, though I am not sure why. Since you are unable to even start tilda you cant reset the background from the preferences window. But you could either try to delete the current config file to use the default values or you could open the config file, look for the background alpha setting and then try to set it to an allowed value.

**Comment by rsvitale** [comment]
I'm not sure how this happened but I had 63 config files all with back_alpha=-65.  Setting the first 4 (the ones I had been using) to 0 fixed the issue.

**Comment by savolla** [comment]
tilda --background-alpha 1
