### ISSUE TITLE
If Tilda is manually dismissed while focused it cannot be pulled down again - intermittent

### ISSUE THREAD

**Issue by Gwyki** [lanoxx/tilda#244]
I am getting an intermittent bug where after some unknown event Tilda starts behaving incorrectly when it is manually dismissed using the 'tilda key' when it has focus. If Tilda is dismissed it cannot be pulled down again until the "window" has lost focus by some other means. Once this happens restarting Tilda does not correct the issue, only a complete system restart seems to resolve whatever is happening.

Ubuntu 16.04, with bundled Unity.
Tilda 1.3.1

I have tried to reproduce the issue under other window managers but the intermittent nature of this problem has made it difficult...

Before I start hacking on the code to try and discover what is happening is there anything I should be aware of? Simple things to try?

edit: Also it seems that _all_ keypresses are silently dropped until focus from the dismissed Tilda instance happens via the mouse.

**Comment by pik** [comment]
You could try compiling the current master with:
`./configure --enable-debug-functions --enable-vte-2.91  --enable-debug` and see if the output of that gives some insight.

**Comment by Gwyki** [comment]
Apologies that this took me so long to look at.

It seems that whatever has changed between Tilda 1.4~alpha, Ubuntu 16.10, and Unity 7.5.0 this issue no longer seems to be happening for me.

Closing.
