### ISSUE TITLE
[RFE] Tilda should be able to present itself on the screen that is currently higlighted in a multi-monitor setup

### ISSUE THREAD

**Issue by thetuxracer** [lanoxx/tilda#246]
Hello, recent convert from guake and I have to say, this is so much better!

Is it possible to have tilda to show itself on the screen that is active? Alongwith transparency, this method is quick for someone to look and type on the same screen.

**Comment by lanoxx** [comment]
Hi

what you mean is that when you use the tilda how key it will be pulled down on the monitor where the mouse is currently? If so then I think we already have an issue for that. Could you please clarify.

**Comment by thetuxracer** [comment]
@lanoxx Ah, you are right, this request is duplicate of https://github.com/lanoxx/tilda/issues/219. I have zero experience with C, let me have a peek and try to understand whats going on.

In the meantime, I am closing this, because duplicate.

Thank you.
