### ISSUE TITLE
tilda visual bug : flashy !

### ISSUE THREAD

**Issue by Aallam** [lanoxx/tilda#249]
The terminal keeps flashing so fast after pulling it down several times (the flashing is like if the terminal shows up and hide so fast automatically)

OS: Ubuntu 14.04
Tilda Version: 1.1.11 (installed using apt)

**Comment by lucky-znk** [comment]
+1 for this issue after pull down tilda then go to desktop by show desktop key(Ctrl+D)
OS: Linux Mint 17.3 Rosa Based on Ubuntu 14.04
Tilda Version: 1.2.4 (coz 1.3+ doesn't support 14.04)
