### ISSUE TITLE
CoreDump Openbox Tilda 1.3.3

### ISSUE THREAD

**Issue by pik** [lanoxx/tilda#252]
Not sure if anyone else has had this? I'll rebuild from master and try to debug this weekend. 

```
Linux 182af44a 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux
Tilda 1.3.3
vte-common 0.44.2-1
vte3 0.44.2-1
```

Coredump:  https://gist.github.com/pik/76e3a70a93e2fb490d8ecdf6ccad0087

**Comment by lanoxx** [comment]
Not sure whats causing this, can you try to get a stracktrace with gdb attached?

**Comment by lanoxx** [comment]
Tilda 1.3.3 is no long supported so I am going to close this.
