### ISSUE TITLE
expand words for special characters via double click

### ISSUE THREAD

**Issue by grafoo** [lanoxx/tilda#256]
:+1:  for tilda checked it out recently and really like it so far

i've got and issue though.

setting
`XTerm*VT100.charClass: 33:48,35:48,37:48,42:48,45-47:48,64:48,95:48,126:48`
in
`.Xresources`
should usually expand "single" words over characters like `/some/path/` which can then be marked via double click, right?!

however tilda does not seem to care about those settings.

is this intentional and if so how can i enable word select of e.g. paths via double click?

**Comment by lanoxx** [comment]
Tilda has a select by word feature that you can configure under the *Title and Command* tab in preferences. That is what controls what makes up a whole word. I am not sure if `XTerm*VT100.charClass` is a considered a standard, that look as if its that is XTerm specific, or not?

Does gnome-terminal make use of this file?

**Comment by egmontkob** [comment]
gnome-terminal obviously does _not_ use xterm's xresources. It has its own (hidden) setting (as of g-t 3.16), see https://bugzilla.gnome.org/show_bug.cgi?id=730632#c33.

**Comment by grafoo** [comment]
the charclass was just a wild guess.
i also didn't realize that my tilda installation was quit dated. why they are doing this is beyond my imagination but the latest opensuse stable ships with version 0.9.6 .

i compiled your latest release and voila everything works like a charm ( feature explosion :tada: )

sorry for the misunderstanding and keep up the great work!

**Comment by lanoxx** [comment]
@grafoo , I am happy you hear that you like tilda, I am glad this issue could be resolved. 

One remark regarding your Linux distribution, You should not expect that every software package is automatically updated to the latest version. This is not how Linux distributions work. Each package has to be manually packaged and updated. For the essential core packages this is usually done by the maintainers of the distribution, in your case OpenSuse, however for other packages and in particular for smaller ones like Tilda there needs to be some maintainer who packages the software each time a new version is released and then uploads it into the distribution archives. I currently do that for Debian whenever I have the time, but it is too much work to do it for every other distribution. I recommend you check the OpenSuse Tilda package for the current maintainer of that package and ask him to upload a new release. Given that 0.9.6 is several years old it is however very likely that the original maintainer of the Tilda package has just disappeared and nobody is currently maintaining that package. This means that some volunteer must be found who is willing to package and maintain the latest Tilda version for OpenSuse.
