### ISSUE TITLE
tilda does not position correctly on multi-monitor setups

### ISSUE THREAD

**Issue by thegreyshadow** [lanoxx/tilda#260]
Using tilda 1.3.3 under both Plasma 5.7 and MATE 1.16 on Slackware64-current.

If I use a dual-monitor setup and even if I check the relevant configuration parameter asking tilda to be centered on the screen, tilda does not center itself in a multi-monitor setup. In these cases, tilda stubbornly appears on the left side of the main screen.

Thanks!

**Comment by lanoxx** [comment]
There have been some changes to multi monitor support and centering code. If this is reproducible with the latest version of tilda please reopen this issue.

**Comment by lanoxx** [comment]
Should have been fixed by 2eba9f584d18949fb8ba0c1553e1d2b8f274cc82 and a9b0c061cf1bca88034452b838a95bc71d457506
