### ISSUE TITLE
Set window title

### ISSUE THREAD

**Issue by thamma** [lanoxx/tilda#265]
The "title" setting is not applied to newly opened tilda instances, thus they are named "tilda". Always reproducable on 4.8.4-1-ARCH using i3wm.

I tried to adress the issue myself, but failed due to the lack of GTK progamming experience.
If you could point me to where the title "tilda" is set, that would resolve my problem.

**Comment by lanoxx** [comment]
If I am not mistaken, then the title is usually set by the shell and tilda just displays that. If the shell does not set a title then it will fallback to showing tilda. So I think that most likely you need to set something in your shell, such as bash to update the title and set it, for example, to the current path.

Take a look at the wiki: https://github.com/lanoxx/tilda/wiki at the bottom you will find a command that should do this.

**Comment by thamma** [comment]
I'm talking about the "initial title" setting, sorry about the confusion. I'm even intentionally disabling the dynamic title option. For instance, if I set the initial title to "foobar" and restart tilda, xprop tells me, that the window title remains "tilda". 

(My use case is mapping the terminal to a specific workspace using i3. However this mapping is reliant on the window class or window title. I created a dedicated configuration to be loaded for the terminal, that's supposed to open on the dedicated workspace using [PR #251](https://github.com/lanoxx/tilda/pull/251), which you should totally merge to master ;) )

**Comment by HKervadec** [comment]
I had the same problem, fixed it in https://github.com/lanoxx/tilda/pull/281.

**Comment by lanoxx** [comment]
Thanks for the pull request. This is now fixed in master.
