### ISSUE TITLE
third and consequent tilda instances start with default prefs and config window open

### ISSUE THREAD

**Issue by cypa** [lanoxx/tilda#266]
third and consequent tilda instances start with default prefs and config window open ... so all my prefs are lost
I use Ubuntu 14.04 with updates and LDXE Lubuntu flavour over openbox

**Comment by lanoxx** [comment]
Each instance keeps its own preferences, when you start more instances then you have previously used then the preferences window will be show to let you create a new configuration. AFAIK this is not a bug.
