### ISSUE TITLE
How you can delete Bash history in Tilda?

### ISSUE THREAD

**Issue by notalentgeek** [lanoxx/tilda#267]
The history of the default terminal in Ubuntu MATE 16.04 can be deleted by using application like BleachBit. However, command histories in Tilda are not deleted. I want to delete command history in Tilda.

**Comment by lanoxx** [comment]
Tilda does not keep any specific history, its the responsibility of the shell to store the history, that is bash by default unless you are using some other shell. I am closing this issue because this is not a feature that belongs into tilda.
