### ISSUE TITLE
Add OSC 52 clipboard-setting support (tmux). 

### ISSUE THREAD

**Issue by fpqc** [lanoxx/tilda#273]
Hey, I wanted to add support for the OSC 52 control sequence setting the system clipboard/primary selection.  Is this something I would need to add into libvte upstream, or could it be done in tilda (and if so, where in the files is tilda parsing OSC ctlseqs)? 

I already added support for this in tmux (processing, emitting was already in for a while) and in suckless st (they refused to integrate the patch into mainline because it uses a b64_pton function call (or a replacement thereof)), and they are difficult.

Tilda is the other Terminal emulator I use, and I'd like to add support here as well.

**Comment by egmontkob** [comment]
VTE's emulation behavior cannot be extended like this by a container application. You'll need to patch VTE. Start with caps.cc, vteseq-n.gperf and vteseq.cc.

**Comment by lanoxx** [comment]
Closing as VTE related. Please open another issue if VTE has an API that we can use for this.

**Comment by egmontkob** [comment]
See also https://bugzilla.gnome.org/show_bug.cgi?id=795774.
