### ISSUE TITLE
Ctrl + Shift + T closes tabs too fast

### ISSUE THREAD

**Issue by dreszczyk** [lanoxx/tilda#277]
It's not closing them all at once, but it's really fast.

**Comment by rustedwolf** [comment]
Yeah, I also noticed that sometimes it closes both tabs, even if I try be careful. Maybe there should be some time given to wait until next action can be executed while holding the combo?

**Comment by pik** [comment]
Not sure if this is something Tilda should handle or if you should consider turning down your key-repeat rate (e.g. `xset r rate`) ?

**Comment by dreszczyk** [comment]
I don't have such problem in other programs (chrome, gnome terminal, all IDEs.)

**Comment by lanoxx** [comment]
There used to be a bug in an older version of tilda which caused two tabs to be closed at once. This bug has since been fixed. Maybe you are still running an older version where this bug is not uet fixed? Which version do you use?

**Comment by rustedwolf** [comment]
Tilda 1.3.1

**Comment by lanoxx** [comment]
The fix landed in Tilda 1.3.2, particularly 35252b2417f68fc4845622d12ee3df6e12a5e1a2,

You can find the whole commit history for the tilda-1-3 branch here:
https://github.com/lanoxx/tilda/commits/tilda-1-3

Please note that Tilda 1.3.4 has been released on 14th of May 2016. I suggest you report a bug to your distribution and ask them to upgrade to the latest version of Tilda.
