### ISSUE TITLE
Tilda closes when I press ALT or ALTGR

### ISSUE THREAD

**Issue by nextgenthemes** [lanoxx/tilda#280]
Ubuntu 16.10

This only happens when I have the "hide when focus is lost" setting is active. I need to press altgr to type certain characters like ~ on keyboard.

I think this may have to do with the fact that ubuntu shows the OCD for program text menus on alt press. This happens when i disable the setting. Tilda loses focus because the OCD pops up. For ALTGR nothing happens though but may still be related.

**Comment by lanoxx** [comment]
I don't think there is anything that can be done. If Ubuntu is using this button to focus some other widget, then tilda will lose focus. The only thing that you could do is disable to hide when focus is lost option.
