### ISSUE TITLE
Right click url -> copy

### ISSUE THREAD

**Issue by sanderboom** [lanoxx/tilda#287]
A seemingly simple and productivity enhancing update: right click an URL -> click 'copy' should copy the URL to clipboard. 

AFAIK Tilda now offers 2 options: 
- select the whole URL and 'copy', or
- click the link, and the browser is opened. 

It would be great if just the URL could be copied at once. To paste in an browser (window/tab) of choice.

Thanks for looking into this!

**Comment by alexboutros** [comment]
Was this ever changed?

**Comment by lanoxx** [comment]
I decided to implement this as a new entry titled "Copy Link", see screenshot:

![image](https://user-images.githubusercontent.com/691311/74187779-883b4580-4c4d-11ea-86c1-ef699d6c3ceb.png)

The entry is only enabled if the popup is opened in the context a link.
