### ISSUE TITLE
Cannot be transparent under Gnome 3.10

### ISSUE THREAD

**Issue by Cysu** [lanoxx/tilda#29]
It seems that the recent upgrade of vte3 cause the problem. Will it be fixed in the future?

![tilda](https://f.cloud.github.com/assets/1159230/1405511/7d23de48-3d2f-11e3-9410-947800cacc8c.png)

**Comment by ingmarolsson** [comment]
Please have a look at my pull request #121. At least it solves the transparency issue for me. I'm on Ubuntu 14.04 with GNOME Shell 3.10.4.

**Comment by ingmarolsson** [comment]
And I also want to point out that I like your software so much, I chose to spend the time to solve the transparency issue instead of trying to find another terminal emulator :).

**Comment by lanoxx** [comment]
Hi everyone. I have pushed the fix provided by @ingmarolsson as it fixes the problem for Gnome Shell. I would like to ask everyone to check if this also fixes the issues with other desktops and window managers, if not please open another bug report as this one was specifically for Gnome Shell.

**Comment by daper** [comment]
Fixed for Elementary OS with Gala 0.1.0 Great! and thanks.
