### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by thedrow** [lanoxx/tilda#300]
The last release was in 2016. Meanwhile there have been some advances in the project.
Can we release a new version?

**Comment by lanoxx** [comment]
I will try to make a release in November so that it can make it into Ubuntu 18.04.

**Comment by lanoxx** [comment]
Done today. I plan to upload a package to Debian soon and hopefully that will be automatically synchronized into Ubuntu 18.04 before their feature freeze. For other Linux distributions the respective maintainers will need to package and release the new version.
