### ISSUE TITLE
Hyper key support in keybinding?

### ISSUE THREAD

**Issue by mooreniemi** [lanoxx/tilda#304]
Don't believe this is related to #82.

Using xmodmap I have my Caps Lock key set to be Hyper_L. I like to use Hyper+d to trigger my terminal.

This is considered an invalid keybinding in Tilda but I am unsure why.

Will this be supported or should I just use something else to map Hyper+d -> F1?

**Comment by lanoxx** [comment]
Its not possible to bind to caps_lock, this is not a modifier that GTK+ can grab. Infact there is also code in place that ignores modifiers such as numlock, scrolllock and capslock.

**Comment by sespinoza-dev** [comment]
It's not exactly what you asked, but I was able to bind CapsLock in Ubuntu by mapping CapsLock to the Menu key.

In Ubuntu:
Keyboard Preferences -> Layouts -> Options -> Caps Lock Behavior -> Make Caps Lock and additional Menu key.

Then go to Tilda
Preferences -> keybindings -> Pull down Terminal.  and use CapsLock, it will appear "menu" as the one you selected, but it will do the trick, and your CapsLock now will now work as a pull-down terminal.

Cheers!
