### ISSUE TITLE
Multi instance & multi-monitor not working as expected

### ISSUE THREAD

**Issue by laymonk** [lanoxx/tilda#307]
I am not sure what the official situation regarding supporting the running of multiple instances.  

However, seeing the multiple ~/.config/tilda/config_{0,1,n}, I assumed full support and set about trying to get two instances running at the same time .. but bound to different activation keys.

I would typically launch as follows (assuming _0,_1,_n is understood by tilda):
```
tilda 0
tilda 1
```

Well, what I have seen is inconsistency in the relationship between the config files, and the parameter given to tilda when invoked.   Sometimes it seems like tilda totally ignores the parameter and loads whichever config it likes .. at other times it seems to correlate the parameter with the config number.

Throw multi-monitor (as in have both instances pop up at two different monitors) and total confusion ensues .. the two instances seem to pick configs at random .. and both end up running in window/monitor-0 (but their configs think that is window-1) .. 

So, main issue here is that
>  * I am seeking an understanding of how multiple tilda instances should be used
> * I would also like to understand what the option 'Appearance --> Monitor' actually means.  Does it refer to each monitor in a multi-monitor system, for instance?

Thanks ..

**Comment by lanoxx** [comment]
There is no need for such a parameter. Its as simple as running tilda twice. The instance started first will use config_0 and the next started will use config_1.

**Comment by lanoxx** [comment]
Appreance  --> Monitor refers to a particular monitor in a multi-monitor setup.
