### ISSUE TITLE
Make fullscreen persistent setting

### ISSUE THREAD

**Issue by yunake** [lanoxx/tilda#32]
This is a feature request: you can make tilda's window fullscreen by selecting appropriate setting in the context menu, but this is not preserved across restarts of the app.

Is it possible to make this setting persistent? Or would it be perhaps more feasible to add this as a knob to the "appearance" tab in the general settings window?

**Comment by x2b** [comment]
@lanoxx how does that look?

**Comment by yunake** [comment]
*love*
