### ISSUE TITLE
Cannot build tilda from git : callback_func.c seems to be missing.

### ISSUE THREAD

**Issue by FredBezies** [lanoxx/tilda#320]
I tried to build from git tilda in order to upgrade tilda-git PKGBUILD on ArchLinux Users Repository.

I cannot get it to build. Either using PKGBUILD or official instructions, build process is broken quickly:

```
fred@fredo-arch ~/tilda/build (git)-[master] % make --silent
Making all in po
make[3]: *** No rule to make target '../../src/callback_func.c', needed by 'tilda.pot-update'.  Stop.
make[2]: *** [Makefile:236: ../../po/tilda.pot] Error 2
make[1]: *** [Makefile:908: all-recursive] Error 1
make: *** [Makefile:521: all] Error 2
```
Known bug?

**Comment by lanoxx** [comment]
I recently removed that file. Did you refresh the build system by running the autogen.sh script. Your configure files might be out of date.

**Comment by FredBezies** [comment]
Tried from scratch every single time. And every single time, this error appears.

**Comment by egmontkob** [comment]
I can confirm this bug with a fresh git clone. A reference to `callback_func.c` is still present in `po/POTFILES.in`.

**Comment by FredBezies** [comment]
@egmontkob thanks for the tip.

@lanoxx removed `/src/callback_func.c` line from `po/POTFILES.in` and it worked.
