### ISSUE TITLE
search bar should default to find 'prev'

### ISSUE THREAD

**Issue by voidplayer** [lanoxx/tilda#326]
Usually, you want to search backward, not forward :)

ctrl + shift + f, type term, enter to find :)

**Comment by lanoxx** [comment]
I will consider this for the next release of tilda (e.g. 1.5). I plan to add a checkbox in the search bar with title 'Enter searches backwards' that controls the search direction on enter.

**Comment by lanoxx** [comment]
This has been fixed in commit 5254d3cca981e1a6d78fb89762f7fb3d34b766ce and will be included in tilda 1.5. I have just switched the default to backwards but not added a configuration option.
