### ISSUE TITLE
Config_0 symlink get overwritten 

### ISSUE THREAD

**Issue by 2E0PGS** [lanoxx/tilda#327]
So I have symlinked my config for Tilda. The laptop has different settings for display but Tilda seems to handle that. However the symlink gets overwritten with a copy of the config file without spaces after the options. For example on my desktop I have this in the config: `gototab_3_key = "<Alt>3"` but on my laptop I have `gototab_3_key="<Alt>3"` and its like this for all lines.

I think this is why Tilda is overwriting my symlink. Besides that it does not change any options in the config. Any ideas?
 
Both laptop and desktop are running: Tilda 1.3.1
  
Desktop is Ubuntu 16.04. Laptop is Ubuntu 17.04.

**Comment by 2E0PGS** [comment]
Ok so it seems tilda overwrites the config symlink if the Preferences are opened and closed. It must just re save all its settings by overwriting the file. Since there is no cancel or save button only close it always writes the config on closing Preferences. Perhaps consider appending instead of deleting and recreating the file since this destroys symlinks and possibly file permissions.

**Comment by ri-aje** [comment]
is there any progress here? it's been a few months since opening. this basically destroys the ability to manage tilda config together with other configs with git repo.

**Comment by randptr** [comment]
Yah, I have the same issue... I wanted to add my config file to source control by symlinking it to a file inside the repo, but tilda always overwrites my symlink :(
Will this 'feature' be available in a near future?

**Comment by lanoxx** [comment]
Fixed by 69b32d55c2f8d430734f5c161e59fc50f88436a1
