### ISSUE TITLE
CTRL+W quits Tilda

### ISSUE THREAD

**Issue by hymair** [lanoxx/tilda#329]
![image](https://user-images.githubusercontent.com/21025134/34915868-0a95edca-f92e-11e7-9238-c83821e1d2af.png)

As you can see option is unchanged. All of a sudden CTRL+W quits Tilda instead of honoring the option.

Any ideas are very very welcome, this is driving me insane.

Vanilla Arch + XFCE

**Comment by zaken** [comment]
I thought it fixed itself after some reboots but it's back again.

If it's of any help when I start tilda from a terminal like:

```bash
➜  ~ tilda
Tilda has started. Press grave to pull down the window.
*** I open Tilda and press CTRL + W ***
[1]    25306 segmentation fault (core dumped)  tilda
➜  ~ 
```

**Comment by lanoxx** [comment]
Which version of tilda are you using?

**Comment by lanoxx** [comment]
A stack trace would be useful to debug this. Without some more information what tilda is doing at the moment when it crashes I will not be able to reproduce this problem. You can also try the latest version and see if that helps.

**Comment by lanoxx** [comment]
Unfortunately I cannot reproduce this here. If you can still reproduce this with Tilda 1.5.0, then please submit a stacktrace or a coredump and I can try to debug this further.
