### ISSUE TITLE
When using keybinding for close tab, two tabs are closed

### ISSUE THREAD

**Issue by paveldvoinos** [lanoxx/tilda#330]
When I try to close tab via context menu, tab closes correctly.
When I try to close tab via keyboard shortcut (ctrl+shift+w for me), two tabs are closed.

I tried it with opening more tabs, looks like Tilda closes current tab and previous before it.

**Comment by lanoxx** [comment]
This issue has been fixed a long time ago. You are most likely using an old version of Tilda.
