### ISSUE TITLE
Tilda's settings & functions are an utter mess.

### ISSUE THREAD

**Issue by Jakecheslekov** [lanoxx/tilda#331]
WOW. I can't believe I'm forced to use this terminal on Void Linux. What are you doing with this thing!? You actively develop this thing???  

The Pull Down Terminal option DOES NOT EVEN WORK with the settings window open -.- 
I click the button to make it unhide AND THE HEIGHT EITHER SHRINKS OR THE Y POSITIONING GETS MESSED UP!!!!!! ARE YOU KIDDING ME? 

I try to increase the height & it screws up the Y positioning, I try to move the Y positioning & then it screws up the height!! What is this nonsense?! Get it together man! 

Look at Guake. Guake keeps it simple AND IT ACTUALLY WORKS.

**Comment by lanoxx** [comment]
This kind of unconstructive rant will not help you in any way. Please provide more information and explain clearly what the problem is. Which version are you using.

**Comment by lanoxx** [comment]
Also note that this is a project I am doing in my spare time. I am not paid for this. If you have a problem you can always try to fix it by your self and send me a pull request.
