### ISSUE TITLE
Unable to resize

### ISSUE THREAD

**Issue by lpvm** [lanoxx/tilda#332]
Is it possible or not to resize tilda terminal?  I cannot do it.
I'm using version 1.4.1 in XFCE.

**Comment by lanoxx** [comment]
It should be possible. Last time I tried it still worked. Pleae post most information about your environment. Which window manager are you using?

**Comment by lanoxx** [comment]
I just tried again with the latest version and resizing works perfectly here.

**Comment by lpvm** [comment]
Hi lanoxx,

There's no change in cursor when at the border of the Tilda terminal.  ALT + right mouse button doesn't resize, too.
Could it be some preference setting?

Using XFCE 4.12
Tilda 1.4.1
gtk+-2.24.32_1
gtk+3-3.22.26_1

What other info do you need?

**Comment by lanoxx** [comment]
You cannot resize Tilda with the mouse. Right click and open the Preferences. The Window is resized from the Apperance tab.

**Comment by lpvm** [comment]
Ok, it's explained.  Never thought it could not be re-sizable like the other windows, but never used a drop-down terminal before...
Thank you for your time.
