### ISSUE TITLE
Prevent stealing focus from Tilda

### ISSUE THREAD

**Issue by mir3z** [lanoxx/tilda#333]
Consider the following scenario: 
1. I'm starting an application which takes some time to be up and running.
2. While the application is starting I open tilda with hotkey. I have "always on top" option set.

Actual behavior: when application is ready it steals focus from tilda. Often I type something in tilda during application startup and I have to press hotkey several times so that tilda can reclaim focus.

Expected behavior: I would like tilda *always* has focus, as long as it is active, regardless of what is happening in the background. Is it possible?

**Comment by voidplayer** [comment]
This is a wm setting. I dont think tilda can do much about this. Maybe try to steal focus all the time artificially, but this would step out of their scope slightly imho

For example, in kwin (kde window manager that you can use with other desktops, like xfce) all windows have properties and you can set 'focus stealing prevention' on them

**Comment by lanoxx** [comment]
As @voidplayer said, there is not much tilda can do about this as this is managed by the window manager.
