### ISSUE TITLE
Drop libvte 2.90 support

### ISSUE THREAD

**Issue by egmontkob** [lanoxx/tilda#334]
libvte 2.91 is almost 3.5 years old.

libvte 2.90 has been abandoned for more than 2 years. It contains a security/privacy issue that scrollback contents are written to disc unencrypted, the fix will not be backported to this branch.

All terminal emulators that support GTK3-based VTE have for quite some time now upgraded to use 2.91.

Leading distributions (e.g. Debian, Ubuntu, Fedora) dropped libvte 2.90 about a year ago.

I see no reason to keep libvte 2.90 support around, and dropping it could hopefully lead to noticeably cleaner code.

**Comment by lanoxx** [comment]
Yes, I am planning to drop it, now that I have released 1.4.

**Comment by lanoxx** [comment]
Fixed in 095ece37355f3c8f4951b354af2f64028c706d5b
