### ISSUE TITLE
Issues launching tilda into i3 when animations turned on

### ISSUE THREAD

**Issue by akhilcjacob** [lanoxx/tilda#335]
When I turn on the animations for Tilda and pull down the terminal using the hotkey the terminal fills the upper part of my screen and then becomes unresponsive. Picture shown below:
![image](https://user-images.githubusercontent.com/7051918/36463108-ad5e7656-1695-11e8-80b5-f4447cab47ef.png)

**Comment by lanoxx** [comment]
Please post the current version of Tilda which you are using. Note, that since version 1.4.x the animation behavior has changed. We are now setting the window type to `_NET_WM_WINDOW_TYPE_DOCK` during the animation. If you are using version 1.4 and then this might be the reason for this issue.
