### ISSUE TITLE
po/README file looks outdated

### ISSUE THREAD

**Issue by hosiet** [lanoxx/tilda#338]
`po/README` file says the translation is hosted on Launchpad. However, https://translations.launchpad.net/tilda/trunk/+pots/tilda seems severely outdated now.

Now that I want to contribute some translation, should I directly submit PR now? If so, that file should be updated or removed.

**Comment by lanoxx** [comment]
I guess submitting a pull request is currently the best option. I am not currently monitoring that launchpad site.

**Comment by hosiet** [comment]
@lanoxx The fix is present in Pull Request #339 .
