### ISSUE TITLE
F11 Fullscreen does not return back to original size

### ISSUE THREAD

**Issue by esemeniuc** [lanoxx/tilda#340]
System: Antergos latest with Cinnamon
Version: tilda 1.4.1
Settings: see here: https://imgur.com/a/tHesh
When going into full screen mode (F11), the width and height settings prior to using full screen is not restored. Instead, it will use about 70% of the screen width and height instead.

**Comment by voidplayer** [comment]
This is fixed in master

Either compile it yourself or wait for a new release :)
