### ISSUE TITLE
Transparency is not working on Raspbian on RPi.

### ISSUE THREAD

**Issue by INDIGI-CO-UK** [lanoxx/tilda#343]
I've tried to all 'hints' from other topics, but transparency is not working on Raspbian on RPi.

transparency is 100%
black alpha=0

and I have black background.

All other settings from config_0 are respected.

Any ideas?

Ps. I've installed Tilda ONLY for transparency and 'on desktop' effect :)

**Comment by lanoxx** [comment]
Maybe your window manager does not support transparency, did you try to run gnome-terminal to see if transparency works there?

**Comment by lanoxx** [comment]
There are several factors here that can impact this:

1. Tilda tries to detect at start up if the window manager supports compositing which is required to enable transparency. If compositing is not available then the tilda window will not be transparent. If tilda is placed into autostart, then sometimes it can happen that tilda is started before the window manager and the compositing functionality is not available yet. In this case restarting tilda helps.
2. If may be the case that your window manager generally does not support compositing or that its not enabled in your window manager. In this case there is not much that tilda can do.

If you are sure that your window manager supports compositing, then please reopen.
