### ISSUE TITLE
Change Shift+Click to open URL

### ISSUE THREAD

**Issue by totszwai** [lanoxx/tilda#368]
Could you change the behavior of Tilda following URL? I don't want to accidentally have it opens URL when I click on it. There is no keybinding for this behavior.

**Comment by lanoxx** [comment]
Originally it was required to press CTRL to open a link but I found that to be difficult to discover for users so it was removed in this commit: d7d2b5ccf608e7c2f8188a5c0ce3233d1f96c7f6.

Not sure what would be a better usability solution but I am reluctant to just bring it back a different modifier key such as Shift.

**Comment by tiandrey** [comment]
Please bring it back (or add switch in preferences). Pressing Ctrl for opening links is used at least in mate-terminal (bet gnome-terminal has the same behavior).
Right now even if I try to select part of  an URL in Tilda, I end up with this URL opened in browser.

**Comment by lanoxx** [comment]
As several people have complained about this I am going to bring this back in the next tilda minor release.

**Comment by r0e** [comment]
I was actually working on a PR for this (if you were willing) but glad to see you're on top of this.

**Comment by lanoxx** [comment]
There is now a new option in the preferences to enable this. I have decided to activate it by default:
![image](https://user-images.githubusercontent.com/691311/101989298-ba6b6880-3c9f-11eb-930f-9f7dbb684956.png)
