### ISSUE TITLE
Incorrect handling of ANSI escape sequences

### ISSUE THREAD

**Issue by darnir** [lanoxx/tilda#370]
While using a program that emits many ansi sequences in order to control the output on the screen, I noticed that tilda doesn't seem to handle them correctly. I've captured the raw output and it is available here: http://ix.io/1poQ
The commands in this file seem to work just file when output on konsole, but they cause weird upwards motions on tilda.

**Comment by egmontkob** [comment]
https://gitlab.gnome.org/GNOME/vte/issues/48

**Comment by darnir** [comment]
Thanks! I guess I'll have to deal with them on this issue.
