### ISSUE TITLE
Tilda getting stuck with solid black background color when trying to toggle transparency

### ISSUE THREAD

**Issue by toorandomenvi** [lanoxx/tilda#372]
When this happens i get this error : 
(tilda:4706): Vte-CRITICAL **: 20:34:19.752: void vte_terminal_set_color_background(VteTerminal*, const GdkRGBA*): assertion 'valid_color(background)' failed

this problem might also be linked to settings for transparency not being saved when i restart Tilda. If i force the transparency level from 100 to another value and then back it works again until i toggle it again

I have already tried reinstalling Tilda few times with no success

OS: Xubuntu 18.04 (fresh installation)

**Comment by toorandomenvi** [comment]
After restarting my laptop the config was edited back to the wrong value by tilda so a temporary work around is to set the config_0 file to read only after fixing the Back_alpha value

**Comment by lanoxx** [comment]
Thanks for reporting this bug, I think I recently fixed a bug concerning negative back_alpha values in the configuration (see commit b504ea0177cd91ed42cc326e684d702ed021e28d).

This should be fixed in the next release.
