### ISSUE TITLE
Tilda only taking up small amount of screen

### ISSUE THREAD

**Issue by gitsnow** [lanoxx/tilda#374]
I just upgraded to Ubuntu 18.10 and I'm on Tilda version 1.4.1-2.  I have Tilda opening from the right side of my screen.  It used to work using a percentage or pixel amount of the screen, but now that setting doesn't appear to work.  Whenever I show Tilda, it only takes up about an inch of the screen.  I've tried changing the percentage and pixel amount, but it always opens up to that tiny size.  It worked fine on Ubuntu 18.04.

**Comment by CottonEaster** [comment]
I find - on Mint Cinnamon - that setting the height percentage only works (sticks) if one moves the caret to another field before leaving the configuration window.

Tilda 1.4.1

**Comment by lanoxx** [comment]
There have been some changes to the positioning and sizing code. Please reopen if this is still present in tilda 1.5.0. If this is still present in the latest version I will also need some more information in order to fix this.
