### ISSUE TITLE
taskbar window name is untitled window

### ISSUE THREAD

**Issue by panpakos** [lanoxx/tilda#375]
I dont see any option in settings to chamge it so how does it generated? 
xfce 4.12, debian unstable, tilda 1.4.1-2

**Comment by lanoxx** [comment]
Fixed by 5b5684a7f2b5ffe0196003feb827af79856214d8 and 9e7b9b37ed05f732c1fcf47a7ee08732535292c7 and f1221bfcd34934dbf4cfe6652375e2dcc4b742c8. This will be in version 1.5 of tilda.
