### ISSUE TITLE
Preferences window opens behind terminal proper, when launched from autostart openbox

### ISSUE THREAD

**Issue by bitshiftnetau** [lanoxx/tilda#380]
Pretty self-explanatory, the preferences window essentially opens behind the terminal window when Tilda is launched from openbox autostart. If I quit the terminal after login and relaunch from the openbox menu, then the preferences menu opens in front of the terminal. 

Arch Linux: 4.19.16-1-lts
Openbox: 3.6.1
Compton: 4.0.1

Here is my openbox/autostart file. NOTE: altering the order or options has had no effect. 

nitrogen --restore 
compton -b -i 0.7 -e -m --config /home/access/.config/compton.conf 
tint2 -c /home/access/.config/tint2/tint2rc &
conky -c /home/access/.config/conky/conky_system.conf 
conky -c /home/access/.config/conky/conky_fs.conf 
conky -c /home/access/.config/conky/conky_battery.conf 
conky -c /home/access/.config/conky/conky_network.conf 
conky -c /home/access/.config/conky/conky_vpn.conf & 
tilda -g /home/access/.config/tilda/config_0 &
pasystray

Here is my config_0:

tilda_config_version="1.4.1"
# command=""
font="DEC Terminal 12"
key="<Shift>space"
addtab_key="<Shift><Control>t"
fullscreen_key="F11"
toggle_transparency_key="F12"
toggle_searchbar_key="<Shift><Control>f"
closetab_key="<Shift><Control>w"
nexttab_key="<Control>Page_Down"
prevtab_key="<Control>Page_Up"
movetableft_key="<Shift><Control>Page_Up"
movetabright_key="<Shift><Control>Page_Down"
gototab_1_key="<Alt>1"
gototab_2_key="<Alt>2"
gototab_3_key="<Alt>3"
gototab_4_key="<Alt>4"
gototab_5_key="<Alt>5"
gototab_6_key="<Alt>6"
gototab_7_key="<Alt>7"
gototab_8_key="<Alt>8"
gototab_9_key="<Alt>9"
gototab_10_key="<Alt>0"
copy_key="<Shift><Control>c"
paste_key="<Shift><Control>v"
quit_key="<Shift><Control>q"
title="Tilda"
background_color="white"
# working_dir=""
web_browser="firefox"
increase_font_size_key="<Control>equal"
decrease_font_size_key="<Control>minus"
normalize_font_size_key="<Control>0"
# show_on_monitor=""
word_chars="-A-Za-z0-9,./?%&#:_"
lines=10000
max_width=1440
max_height=892
min_width=1280
min_height=760
x_pos=0
y_pos=0
tab_pos=0
expand_tabs=false
show_single_tab=false
backspace_key=0
delete_key=1
d_set_title=0
command_exit=2
scheme=0
slide_sleep_usec=20000
animation_orientation=0
timer_resolution=200
auto_hide_time=2000
on_last_terminal_exit=0
prompt_on_exit=true
palette_scheme=0
non_focus_pull_up_behaviour=0
cursor_shape=0
# show_on_monitor_number=0
# title_max_length_flag=false
title_max_length=25
palette = {11822, 13364, 13878, 52428, 0, 0, 20046, 39578, 1542, 50372, 41120, 0, 13364, 25957, 42148, 30069, 20560, 31611, 1542, 38944, 39578, 54227, 55255, 53199, 21845, 22359, 21331, 61423, 10537, 10537, 35466, 58082, 13364, 64764, 59881, 20303, 29298, 40863, 53199, 44461, 32639, 43176, 13364, 58082, 58082, 61166, 61166, 60652}
scrollbar_pos=2
back_red=3813
back_green=6573
back_blue=14855
text_red=20046
text_green=39578
text_blue=1542
cursor_red=65535
cursor_green=65535
cursor_blue=65535
scroll_history_infinite=false
scroll_on_output=false
notebook_border=false
antialias=true
scrollbar=false
grab_focus=true
above=true
notaskbar=false
bold=true
blinks=true
scroll_on_key=true
bell=false
run_command=false
pinned=true
animation=true
hidden=false
set_as_desktop=false
centered_horizontally=false
centered_vertically=false
enable_transparency=true
# double_buffer=false
auto_hide_on_focus_lost=false
auto_hide_on_mouse_leave=false
title_behaviour=2
inherit_working_dir=true
command_login_shell=true
start_fullscreen=false
confirm_close_tab=false
# image=""
# scroll_background=false
# use_image=false
transparency=20
back_alpha=26175

If this is nothing obvious and a patch isn't likely, I'm more than happy to pull and patch. Tbh I was going to get involved anyway since I'm just starting to contribute on Compton as well :)

**Comment by lanoxx** [comment]
Can you still reproduce this with the latest version of tilda on the master branch?

**Comment by lanoxx** [comment]
Closing this, if you can reproduce it with the latest version of tilda, then please reopen.
