### ISSUE TITLE
Tilda creates multiple config files at random, when not specfiying a config

### ISSUE THREAD

**Issue by bitshiftnetau** [lanoxx/tilda#381]
I'm guessing there is no checks to see if a config already exists? Or maybe there is but it doesn't work every time, as this would happen at random until I found out there exists an option for specifying config files. 

Again, happy to pull and patch :)

**Comment by lanoxx** [comment]
The way tilda works is that each new process creates and uses its own config file numbered from 0 to n. So if you have two tilda instances running, then you should have config_0 and config_1.

**Comment by lanoxx** [comment]
Closing, since it works as intended.
