### ISSUE TITLE
Tilda won't start

### ISSUE THREAD

**Issue by Metraf** [lanoxx/tilda#385]
Tried purging config files, uninstalling and so on, always getting this error when launching since updated OpenSuSe Tumbleweed not so long ago : 
~> tilda
free(): invalid pointer
Abandon (core dumped)
~>

**Comment by lanoxx** [comment]
Which version of tilda are you using?

**Comment by lanoxx** [comment]
A backtrace would be very useful, or the core dump, or at least some other information that could help identify this problem. Without more information it will be impossible to diagnose this problem. I am closing this bug for now. If you can add more information I can take another look. Please reopen this bug if you are able to add more information.
