### ISSUE TITLE
Cursor stops blinking

### ISSUE THREAD

**Issue by Kzer-Za** [lanoxx/tilda#394]
Open Preferences window, General tab, tick the "Cursor blinks" option. Close the Preferences window. The cursor will blink exactly 9 times, then it stops blinking and just stays in "on" state.

It starts blinking again if you:
1. hide the Tilda window and open it again,
2. switch to another tab,
3. open and close Preferences window.
4. type anything.

In all these cases the cursor will blink 9 times, then stop blinking. It does not depend on the cursor shape, but is visible the most with the Block cursor.

My Tilda version is 1.4.1-1.1, distro is Manjaro, kernel 4.19.56-1, NVidia proprietary drivers, shell is zsh.

**Comment by egmontkob** [comment]
This is intentional in all GTK apps, to save resources (CPU, battery). Open `dconf-editor` and configure `/org/gnome/desktop/interface/cursor-blink-timeout` to your liking (e.g. to an extremely large value to keep it blinking practically forever).

**Comment by Kzer-Za** [comment]
It does not seem to work. I have set it to the maximum of 2147483647, tried setting it to approximately half a maximum, the result is the same: the cursor blinks for 10 seconds, then stops.

**Comment by egmontkob** [comment]
Maybe it depends on the desktop, too; I'm not sure. What desktop do you use? There's an indirection that VTE queries `gtk-cursor-blink-timeout`, depending on the desktop maybe it comes from another dconf setting rather than the one I showed.

**Comment by Kzer-Za** [comment]
I use XFCE. (Just in case, I have tried restarting the system after changing the setting).

**Comment by egmontkob** [comment]
https://bugs.launchpad.net/ubuntu/+source/vte2.91/+bug/1798481 and https://askubuntu.com/q/1070907 are relevant, I'm afraid there was no conclusion and Xfce might not support the blink timeout setting.

**Comment by Kzer-Za** [comment]
Oh, the topic starter at https://bugs.launchpad.net/ubuntu/+source/vte2.91/+bug/1798481 actually found a working solution: manually adding /Gtk/CursorBlinkTimeout with integer type and a custom value to xsettings section of Settings Manager of XFCE.

**Comment by egmontkob** [comment]
Glad to hear it, apparently I didn't read / remember that thread precisely :)
