### ISSUE TITLE
Ligature support?

### ISSUE THREAD

**Issue by umnikos** [lanoxx/tilda#402]
There is this nice font called [FiraCode](https://github.com/tonsky/FiraCode) that only *displays* a group of characters as if they're Unicode without actually inserting any Unicode into your code. This is called "ligatures" and while they work in an emulator such as Konsole it doesn't work in Tilda. Is support for ligatures something that is planned in the future?

**Comment by lanoxx** [comment]
Font handling would need to be implemented in the VTE library not in tilda. The option to configure the font delegates font handling to the VTE library. I don't thing this is something that could be implemented in tilda, but if VTE supports it, then tilda should support it too.
