### ISSUE TITLE
Url-parsing includes closing squarebrackets, also when the openen one is before

### ISSUE THREAD

**Issue by demlak** [lanoxx/tilda#405]
Hi,
i'm using tilda 1.5.0 and when there are urls detected, the detection does not reflect beginning of square brackets before URL.

for example `here.. the link! [https://fdsgdf.com/gfhsjfg/fdh/hfjkdg] take a look!`
is detected as `https://fdsgdf.com/gfhsjfg/fdh/hfjkdg]`

i'm not sure if this is a real bug.. or just not realy good to handle

**Comment by lanoxx** [comment]
I have been working an update of the matching code which you can find on the `wip-pcre` branch. The new code is now able to match also Numbers, Email addresses, and file URLs, so I had to change the functionality of the context menu a little and I would like to receive some feedback on the UI before I include this into the master branch.

The matching code now detects the typo of the matched token and updates the context menu according to the match type. Depending on the type it is possible to copy the matched token or also open it.

Email matched:
![tilda-context-menu-email](https://user-images.githubusercontent.com/691311/99910108-8a5a2680-2cec-11eb-885d-b0477df1eaf5.png)

File URI matched:
![tilda-context-menu-file](https://user-images.githubusercontent.com/691311/99910109-8af2bd00-2cec-11eb-97d2-613b10636062.png)

Number matched (no open link):
![tilda-context-menu-number](https://user-images.githubusercontent.com/691311/99910110-8b8b5380-2cec-11eb-87fb-6700ea9de4d0.png)

URL matched:
![tilda-context-menu-url](https://user-images.githubusercontent.com/691311/99910111-8b8b5380-2cec-11eb-8973-fc23b3349901.png)

**Comment by demlak** [comment]
tried to compile..
```
make  all-recursive
make[1]: Entering directory '/home/demlak/Downloads/tilda-wip-pcre/build'
Making all in po
make[2]: Entering directory '/home/demlak/Downloads/tilda-wip-pcre/build/po'
make tilda.pot-update
make[3]: Entering directory '/home/demlak/Downloads/tilda-wip-pcre/build/po'
make[3]: *** No rule to make target '../../src/menu.ui', needed by 'tilda.pot-update'.  Stop.
make[3]: Leaving directory '/home/demlak/Downloads/tilda-wip-pcre/build/po'
make[2]: *** [Makefile:237: ../../po/tilda.pot] Error 2
make[2]: Leaving directory '/home/demlak/Downloads/tilda-wip-pcre/build/po'
make[1]: *** [Makefile:1130: all-recursive] Error 1
make[1]: Leaving directory '/home/demlak/Downloads/tilda-wip-pcre/build'
make: *** [Makefile:577: all] Error 2
```

**Comment by lanoxx** [comment]
I removed the `menu.ui` files from the sources since the menu is now created dynamically from the code. It seems I forgot to remove it from the translation scripts. I am not quit sure why that did not cause an error on my system. I pushed an update to the branch, please try again.

**Comment by demlak** [comment]
compiling worked..
matching seems also to work.. nice!

eventually link-klicking is broken?
usualy i just set "firefox" as webbrowser option and it worked on other tilda versions. 
Here i have to right click -> open link
Direct clicking link, does not open link

**Comment by lanoxx** [comment]
I added a change which requires that the control key is pressed when a link is clicked. That has been requested in another bug for some time. This change should help to avoid accidentally clicking on the link when trying to copy some text, but it also makes it a bit less discoverable.

For the record, here is a snipped I used to test the matching functionality, that contains examples for *Number*, *URL without schema*, *URL with Schema*, *email without prefix*, *email with mailto prefix* and a *file URI*:

```
echo 12345;                                        # Copy Number
echo www.google.com;                       # Copy / Open Link
echo https://google.com;                     # Copy / Open Link
echo email@example.com;                 # Copy / Send Email
echo mailto:example@example.com;  # Copy / Send Email
echo file:///usr/                                     # Copy / Open File
```

You probably already noticed that the labels adjust and change between *Open ...* and *Send ...*. Also the Send option is omitted for the number match, which means the context menu is one entry smaller for number matches than for other matches and two entries smaller if no match is detected. I am still considering to always show all entries but make them deactivated to ensure the context menu always has the same size. Let me know if you have any preferences.

**Comment by demlak** [comment]
i think, users are very diverse. Maybe it's a good choice to not declare for all, but implement option to modify? this would reflect different workflows of people.

**Comment by lanoxx** [comment]
Added configurable options for the context menu in commit 37aacb16b89c5c39e320ba040ed3c11ab5bbc8de.

**Comment by lanoxx** [comment]
![image](https://user-images.githubusercontent.com/691311/100522903-8460bb80-31ac-11eb-8061-f32a91566e19.png)

**Comment by demlak** [comment]
nice.. but at first i meant this:
> I added a change which requires that the control key is pressed when a link is clicked.

:smiley:

**Comment by lanoxx** [comment]
Issue #368 which tracks match activation handling, I have pushed a commit to master to fix that issue.

**Comment by lanoxx** [comment]
@demlak I have rebased this branch on master and cleaned up the code a little. It now also properly handles OSC 8 hyperlinks (i.e. `printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'`). I think the code is ready to be merged, if you could give it a final test and let me know if you notice any issues that would be great. If you can confirm that it works fine, then I will merge it into master.

**Comment by demlak** [comment]
Awesome!
i just took a short view and did not see any issues

**Comment by lanoxx** [comment]
Pushed with a few small modifications:
* Added license clarifications and headers, since the new `tilda-regex.h` header is `GPLv3 (or later)`.
* Fixed a match opening issue for links missing the `http://` schema prefix (i.e. `www.example.com`).

This is now in master. Thanks for helping to test this.
