### ISSUE TITLE
URL Parsing broken since VTE update to 0.60

### ISSUE THREAD

**Issue by demlak** [lanoxx/tilda#406]
Hey..
URL Parsing is broken since update of vte3 to 0.60.

additional info: https://bugs.archlinux.org/task/65772
quote:

> VTE 0.60 removed the implementation for vte_terminal_match_add_gregex, which has been deprecated since VTE 0.46.
Please file bugs against the individual terminals which were broken.

**Comment by lanoxx** [comment]
Thanks for this info. I have already started to work on a replacement. I will post an update here when I can say more.

**Comment by lanoxx** [comment]
Should be fixed in master now with commit 2ea93d5c. I am also going to backport this to 1.5.x.

**Comment by lanoxx** [comment]
This is now part of the tilda-1-5 branch via commit 33417bc122a1195ef45789a0be4b7c7bb98dbb14 and will appear in 1.5.1 once I do another bug fix release for the 1.5 series. Unfortunately I cannot promise that this will make it into Ubuntu. I will see what I can do.

**Comment by lanoxx** [comment]
The corresponding commit in the master branch is 2ea93d5c52645efe76c68e947879905c8bd469c3.

**Comment by lanoxx** [comment]
I have created a stable release update for Ubuntu 20.04 focal which is currently in the proposed updates and should become available once the package moves into the updates repository.
