### ISSUE TITLE
"Process completed" Toggle feature

### ISSUE THREAD

**Issue by athaa** [lanoxx/tilda#411]
Hello,

Is there any way to toggle on Tilda (on the right tab) when a long process (like a build) complete ?

I think a workaround could be to override my prompt, to send a Toggle DbusAction or use some tool like xdotool to simulate toggle key, when displayed, but that wouldn't activate the right tab and it's ugly.

Any idea ?

If the need is shared and compatible with the project goal, I may code and submit pull request ( I guess it shouldn't be too complex).

PS : I have noted the issue #367 is more or less similar.

**Comment by lanoxx** [comment]
There is an open pull request to add a Dbus Interface to toggle tilda, but its not merged yet, once it has been merged you could add a script to your shell that calls the dbus interface to toggle tilda when your command has completed. Is that what you are looking for?

**Comment by athaa** [comment]
the Dbus + script  should be ok for me.

I have checked for a way to include the behaviour natively into Tilda but if I understood well Tilda does not have knowledge of event of the inner terminal. It does not run command, just send input to the inner terminal, so it can't detect itself the end of a command. I'm right ?

**Comment by lanoxx** [comment]
For each tab in tilda, tilda will either spawn a shell (e.g. bash) or a custom command. Tilda has no knowledge about child processes that the shell or a custom command starts. So there is also no immediate way to detect when a child process of the shell has completed.
