### ISSUE TITLE
Animated pull down setting is ignored

### ISSUE THREAD

**Issue by mikpom** [lanoxx/tilda#413]
Greetings!

I can't disable animated pull down but unticking the corresponding option. 
![tilda_resize](https://user-images.githubusercontent.com/11643719/80439556-01833400-8931-11ea-9553-70f0f1188814.gif)

Other options seem to be working fine.
Running on Linux version 5.6.6-arch1-1 Arch linux with Gnome on Xorg. 

Thanks.

**Comment by lanoxx** [comment]
The animation you are seing is not coming from `tilda` but instead from GNOME Shell (probably the mutter window manager). Not much I can do about it. You could try to switch to another window manager or check if mutter has a configuration option to disable animations.
