### ISSUE TITLE
Is the allow bold option totally removed?

### ISSUE THREAD

**Issue by Pablorg99** [lanoxx/tilda#426]
I've updated Tilda to the new 1.5.2 version in Ubuntu 20.04 and I have noticed that the bold font is appearing in my terminal. After reviewing my settings and checking the repository I have found this commit https://github.com/lanoxx/tilda/commit/ed4a0a5ff2ef11d06668dcca7b414f22c8a57059

I really miss this option and I was wondering if it has just been removed from the ui or I can still disable the bold font

**Comment by lanoxx** [comment]
Starting with version 0.60 of the VTE libary the corresponding function `vte_terminal_get_allow_bold` has been deprecated. The deprecation message now reads:

> `vte_terminal_get_allow_bold` has been deprecated since version 0.60 and should not be used in newly-written code.
There's probably no reason for this feature to exist.

That is why I removed this option in commit `ed4a0a5ff2ef11d06668dcca7b414f22c8a57059`. I never really used that feature, so I have no idea how that impacts you. I you might want to report your use case to the VTE library authors. Unless VTE removes the deprecation and supports the `vte_terminal_set_allow_bold` function again, I don't think I will bring this feature back.
