### ISSUE TITLE
Crash in the midst of typing

### ISSUE THREAD

**Issue by bodqhrohro** [lanoxx/tilda#432]
```
(tilda:271819): GLib-GObject-WARNING **: 14:12:48.183: invalid unclassed pointer in cast to 'GtkNotebook'

(tilda:271819): Gtk-CRITICAL **: 14:12:48.644: gtk_notebook_get_n_pages: assertion 'GTK_IS_NOTEBOOK (notebook)' failed

(tilda:271819): Gtk-CRITICAL **: 14:12:48.644: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
```
I can only tell for sure that the system was under heavy load when it crashed.

**Comment by lanoxx** [comment]
Looks like something ran out of memory and or the stack got corrupted, this should not happen under normal operation and I have no idea how this could be fixed. If you find some way to reproduce this or provide a stack trace, then maybe I can look into it.
