### ISSUE TITLE
Disable bold fonts

### ISSUE THREAD

**Issue by mdcclxv** [lanoxx/tilda#449]
Any way to disable bold fonts? Gnome terminal removed that option and I can't seem to find it in your app either.

**Comment by tronkko** [comment]
You can disable a particular bold font, for example Ubuntu Mono, by creating file ~/.config/fontconfig/fonts.conf with contents:

```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
<match target="pattern">
    <test qual="any" name="family">
        <string>Ubuntu Mono</string>
    </test>
    <test name="weight" compare="more">
        <const>medium</const>
    </test>
    <edit name="weight" mode="assign" binding="same">
        <const>medium</const>
    </edit>
</match>
</fontconfig>
```

However, this will disable bold version of the font from all apps!

**Comment by mdcclxv** [comment]
Noooope, that's an ugly workaround, this should be an option in your terminal's settings. PuTTY allows that, for example.

**Comment by lanoxx** [comment]
Outside of my controll, since VTE removed support for it. Please ask this on the libvte project. If VTE supports it again, we can add it back to tilda.
