### ISSUE TITLE
PCRE2 not supported

### ISSUE THREAD

**Issue by cbjuju** [lanoxx/tilda#454]
I faced the message in the heading of this issues when installing tilda from source. It installed just fine but when I tried to open it from the command line it wouldn't open and this message would appear on the console instead. I solved it by removing some all files related to tilda that were cached by the system and then building tilda [again.](url)

Now I am facing this message again when trying to search something from the search bar. After pressing ctrl+shift+f when I type something into the search field and press enter, it does not do a search. Red text appears over the text field saying "PCRE2 not supported".

I installed tilda on Ubuntu 18.04 from source following the instructions given in HACKING.md.

**Comment by lanoxx** [comment]
This occurs on older versions of Ubuntu (see 5fef1b81e14cbdb032e185b231860babd4d813b7 and 6f1fd4776e76657e0ac673495780c1d8aa7cf199 for some background). I eventually removed the workaround again in commit 2b4dc488a53c212a65df78cf1f61b556e1ee7df5, meaning that for tilda master branch Ubuntu 18.04 is no longer supported. I recommend you upgrade to 20.04 which is the current LTS where this problem should not occur.

The tilda-1-5 branch should still have the compatibility, you can try to build that one.

Note, I usually try to support older distributions and usually make sure that I support the most recent LTS distributions, like Ubuntu LTS and Debian Stable, but not older than that.
