### ISSUE TITLE
Segmentation fault (core dumped) error when launching tilda

### ISSUE THREAD

**Issue by alphaQ314** [lanoxx/tilda#461]
Hi guys, 
Tilda isn't working for me anymore. I get the following error whenever I try to launch it from the terminal. I'm using Ubuntu 20.04.2 LTS x86_64
```
Problem parsing custom command: Text was empty (or contained only whitespace)
Launching default shell instead
zsh: segmentation fault (core dumped)  tilda

```

**Comment by lanoxx** [comment]
This occurs in https://github.com/lanoxx/tilda/blob/master/src/tilda_terminal.c#L491 when there is a problem in argv parsing returned by `g_shell_parse_argv`. If it worked before I am not sure if the behavior of that function recently changed. Do you have anything special in your custom command that could be causing this?

**Comment by lanoxx** [comment]
I wonder why tilda is crashing for you afterwards. Do you have a chance to compile the latest version of tilda and try with a debugger?

If you could capture a stacktrace that shows where tilda is crashing then we can likely fix this.

**Comment by alphaQ314** [comment]
My apologies for the rather delayed response. I switched from ubuntu to arch during the last month. Tilda is working perfectly on archlinux. 
Thank you so much for creating and maintaining Tilda. Cheers!

**Comment by elig0n** [comment]
I have the same problem when `command=""` and `run_command=true` with tilda 1.5.4 on Manjaro Linux. 

```
Problem parsing custom command: Text was empty (or contained only whitespace)
Launching default shell instead

(tilda:822217): VTE-CRITICAL **: 16:03:19.525: void vte_pty_spawn_with_fds_async(VtePty*, const char*, const char* const*, const char* const*, const int*, int, const int*, int, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, int, GCancellable*, GAsyncReadyCallback, gpointer): assertion 'envv == nullptr || _vte_pty_check_envv(envv)' failed
[1]    822217 segmentation fault (core dumped)  tilda              
```
