### ISSUE TITLE
New Config Created/Used After Every Reboot

### ISSUE THREAD

**Issue by InklingGirl** [lanoxx/tilda#478]
As the title says. I set Tilda to launch w/ my desktop, but it keeps creating a new config `config_1`, `config_2`, & prompting me w/ the configuration wizard on every boot instead of just using my already perfectly pre-configured `config_0`. How can I correct this behaviour? Thank you.

**Comment by vredesbyyrd** [comment]
Use the config flag `[-g,--config-file]` to specify what config you want to start your tilda instance with, eg `tilda -g $HOME/.config/tilda/config_0`. See `tilda --help`.

**Comment by InklingGirl** [comment]
> Use the config flag `[-g,--config-file]` to specify what config you want to start your tilda instance with, eg `tilda -g $HOME/.config/tilda/config_0`. See `tilda --help`.

This works, thank you @vredesbyyrd & I hope @hemulin will benefit from this as well.
