### ISSUE TITLE
Unknown option --dbus

### ISSUE THREAD

**Issue by eugenioperea** [lanoxx/tilda#510]
I'm trying to fix the issue with inconsistent keybinding for pulling down the terminal (issue #491), but when I try to launch tilda --dbus I get this: `Error message: Unknown option --dbus` Upon further investigation, I see that I have version 1.5.4, where Github only shows version 1.5.0. I'm lost here. Help?

**Comment by develroo** [comment]
Well looking at the pull requests it has only been added in the last month? 

https://github.com/lanoxx/tilda/pull/495

So I am guessing it has not rolled out to distros yet. I am on Debian testing and have the same version as you. So I might try and compile it myself and see if that works.

**Comment by lanoxx** [comment]
Tilda 2.0.0 is now in Debian unstable and should reach Ubuntu 24.04 before it goes into the Debian import freeze.
