### ISSUE TITLE
KDE (.desktop.in file)

### ISSUE THREAD

**Issue by spaette** [lanoxx/tilda#512]
the KDE Start Menu entry's image doesn't render unless the file extension is added to the .desktop.in file

the terminals as Konsole and XTerm appear under 

Start Menu > System

if GNOME has use for `Categories=`  `System;` and `Utility;` is unclear, if not please consider removing `Utility;`

for consistency with other teminals' .desktop files a `Comment=` line should be added

```
$ cat tilda.desktop.in
[Desktop Entry]
Name=Tilda
Comment=Terminal Emulator
Exec=@BINDIR@/tilda
Icon=tilda.png
Terminal=false
Type=Application
Categories=GNOME;GTK;System;TerminalEmulator;
$ 
```

**Comment by lanoxx** [comment]
I have added a comment and removed the utility category (see 51f5a793ba3f99104b837929ef309613b723251c, a4b073da14f0a02b125c424e7fff4c9fb8ee9269)

I remember that in commit 94ec3d851f4426bc7474063fb5ae8e8a31c37267, the icon extension was explicitly removed to allow theming of the icon and the https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html mentions that the extension can be omitted. So I wonder if this is an issue with KDE. I would like to understand the consequences better before removing it.

**Comment by spaette** [comment]
> like to understand the consequences better

I'll check a couple of Linux distro which are running KDE.

I wouldn't know whether reliance (?) on an `icon-theme.cache` file has a bearing on this circumstance.

Perhaps current Linux distros favour icons in `/usr/share/icons/hicolor subdirectories`.

**Comment by spaette** [comment]
By the way is Debian still shipping Truffa's custom written manpage?

**Comment by lanoxx** [comment]
Its possible that the icon needs to be installed in an additional location, maybe `/usr/share/icons` in addition to `/usr/share/pixmaps`? I would need to take a closer look.

I am in the process of building and uploading tilda 2.0.0 into the Debian archives, if that goes well it should also come with an updated man page. The source for that is now in this repository instead of the debian package sources, so if you want to contribute some changes feel free to prepare a pull request.

**Comment by spaette** [comment]
I only noticed the Slackbuilds.org files for tilda bundle Truffa's custom written manpage.

Feasibly that community and Debian might preferably utilise the manpage generated from the tilda repo itself.

<hr>

It is easy enough to copy the tilda.desktop file to `~/.local/share/applications` and modify it at that location.

Slackware

I'm somewhat curious why KDE's Start Menu isn't picking up the `/usr/share/pixmaps` located tilda.png, absent reinserting as it were the file extension to the Icon= entry in the tilda.desktop file. 

SuSE Linux

I'll check their KDE to see if the similar occurs.

**Comment by spaette** [comment]
_for your review_

the highlighted content is a rewording of the following

```
$ ed -s tilda/data/man/tilda.1.in <<<'43,45p'
is a terminal emulator which is highly configurable. The main distinguishing feature of tilda is that it
uses a configurable shortcut to show and hide the tilda window. This allows users to quickly switch between tilda
and other windows only through keyboard shortcuts. When tilda is hidden it will move
$ 
```


**Tilda** is a terminal emulator which is highly configurable. `The main distinguishing feature is that users can specify keyboard shortcuts to show and hide the tilda window. This allows users to quickly switch between tilda and other windows.` When tilda is hidden it will move outside of the screen until the pull/toggle shortcut is pressed again to show the tilda window. The behaviour of tilda can be configured using the preferences dialog that is available via the context menu. A subset of the options can also be configured from the command line as documented below.

**Comment by spaette** [comment]
SuSE Linux (version 15.4)

Installed via YaST the precompiled tilda results in the start menu icon rendering.

Here's a screenshot of the result in the start menu of the build of the repository clone.

![start-menu](https://github.com/lanoxx/tilda/assets/111918424/093aa654-b0a0-4974-9869-7dcb6356f093)

What to you think about a check for pcre2.h presence?

**Comment by spaette** [comment]
Possibly add something to README.md as below, which may however not take into consideration running Wayland.


```diff
diff --git a/README.md b/README.md
index 4f67c82c..77b9ee40 100644
--- a/README.md
+++ b/README.md
@@ -76,6 +76,19 @@ Other default keybindings are:
  * Shift-Ctrl-W - Close current tab
  * Shift-Ctrl-Q - Exit Tilda
 
+If you want to avert the first run global screen grab by the configuration wizard.
+
+```
+$ mkdir -p ~/.cache/tilda/locks
+$ mkdir -p ~/.config/tilda
+$ cat <<EOF > ~/.config/tilda/config_0
+> key="F1"
+> height_percentage=444958611
+> width_percentage=943257824
+> EOF
+$
+```
+
 # Specifying your own keybinding to hide / show Tilda
 
 We, the developers, have attempted to make the keybinding setting work with as
```

**Comment by spaette** [comment]
Closing as in tilda.desktop the `Categories=`  line had `Utility;` removed and a `Comment=` line  has been added.

Modifying the manpage and/or adding a check for pcre2.h presence is beyond the scope of this issue.

For those unfamiliar with coding for D-Bus/Xwayland the current documentation might seem to appear sparse.

**Comment by spaette** [comment]
@lanoxx 

KDE

![start_menu](https://github.com/lanoxx/tilda/assets/111918424/4de4b42a-aced-4d4a-a68d-47d31653159c)

Perhaps a Comment value which is shorter would be sufficiently concise.

tilda.desktop.in

```
Comment=Terminal Emulator (X11)
```

tilda-dbus.desktop.in

```
Comment=Terminal Emulator (Xwayland)
```
