### ISSUE TITLE
wizard (screen sizes)

### ISSUE THREAD

**Issue by spaette** [lanoxx/tilda#513]
On KDE a first run tilda fills the available screen real estate minus of course that space allocated for the system tray.

On a screen size of 1366x768 dimensions the configuration wizard window will not entirely appear on the screen.

Consider making the default size of the configuration wizard window of the same dimensions as that of the first run tilda.

The foregoing might imply that horizontal and vertical scrollbars be coded for the configuration wizard window.

**Comment by lanoxx** [comment]
I pushed several commits that modernize the dialog and replace deprecated GTK properties. In addition I have wrapped all tabs of the dialog into scrolled windows, this should now allow to resize the dialog properly so that it can fit on smaller screens.
