### ISSUE TITLE
Tagging releases as a release for better looks

### ISSUE THREAD

**Issue by hannes101** [lanoxx/tilda#514]
Hello, 
I noticed that apparently the latest releases are not tagged properly as a release in github. So when you check out https://github.com/lanoxx/tilda/releases it appears that 1.5.0 is the latest one. Although the https://github.com/lanoxx/tilda/tags page shows that actually. 2.0.0 was released last week.
This will probably also show 2.0.0 as the latest release on the start page of the repo.
![image](https://github.com/lanoxx/tilda/assets/11256578/5fb20b45-34ed-42c0-9e4c-59ff4e99fc88)

I think this improves the overall appearance of the project, because it shows the activity, which is there.

**Comment by lanoxx** [comment]
Done: https://github.com/lanoxx/tilda/releases/tag/tilda-2.0.0
