### ISSUE TITLE
Feature request: Add 256 color support

### ISSUE THREAD

**Issue by dennis123123** [lanoxx/tilda#62]
Title says it all really... I'd really like to see Tilda upgraded to support a 256 color terminal

**Comment by egmontkob** [comment]
Just FYI: vte-0.40 and onwards automatically set TERM=xterm-256color.

**Comment by voidplayer** [comment]
Thanks for the info! :)

$ ldd /usr/bin/tilda|grep vte
	libvte2_90.so.9 => /usr/lib/libvte2_90.so.9 (0x00007fcd68da8000)

$ dpkg -S /usr/lib/libvte2_90.so.9
libvte-2.90-9: /usr/lib/libvte2_90.so.9

$ dpkg -l libvte-2.90-9
ii  libvte-2.90-9                                 1:0.36.3-1                             amd64        Terminal emulator widget for GTK+ 3.0 - runtime files

This is debian testing. Lets hope it hits the repos soon ;)

**Comment by egmontkob** [comment]
The API has changed, for vte version 0.40 you need the package libvte-2.91-0 and tilda from git. See also #202.

**Comment by lanoxx** [comment]
This should be fixed with tilda 1.3 and later since we are building with the VTE 2.91 API by default.
