### ISSUE TITLE
Feature request: open new tab in current directory

### ISSUE THREAD

**Issue by uvNikita** [lanoxx/tilda#68]
Add option in settings: "Open new tab in current directory", like in Guake terminal.
If it's enabled, new tab must automatically change directory to same one as was in the previous tab.

**Comment by ColtonDRG** [comment]
Is this optional? I can't find the option to turn it off.

**Comment by lanoxx** [comment]
You can turn it off, but not in the gui. Open the config file and set `inherit_working_dir` to false.

**Comment by ColtonDRG** [comment]
I see, thank you.
