### ISSUE TITLE
Screen failes to refresh when viewing large files when tilda is using a background

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [lanoxx/tilda#92]
This is just a symptom of a more fundemental bug, tilda has some screwy refresh behaviour when the background is on. Using less on a big file is just a reliable way to reproduce it. 

Set tilda to have a background, open a big file in less, and scroll down and the refresh will stop working.

A way around this issue is double buffering, but then the background cuts out.

**Comment by switzel** [comment]
I think this is the same issue although it has nothing to do with large files. When I activate compositing and text is overprinted in Tilda, the text below is not cleared, producing gibberish like this:

![screenshot](https://cloud.githubusercontent.com/assets/5306465/7699106/cb192a2e-fe15-11e4-9c18-c311ae842369.png)

(Here I did a reverse i-search (Ctrl + R) to have Tilda overprint something but it also occurs for the progress percentages during and apt-get install for instance.)
It is hard to say whether the error is in Tilda or in Compiz. I am using a freshly installed Mate 15.04. As far as I can tell, to reproduce you only need to install Mate 15.04, enable software compositing window manager and have Tilda overprint some text.

**Comment by lanoxx** [comment]
I think its unlikely that this bug is caused by tilda it self. It is more likely that is caused by either the VTE library which is responsible for rendering the terminal or compiz. What about gnome-terminal? Does it have the same issues too?

**Comment by switzel** [comment]
No, gnome-terminal doesn't have the same issue.

**Comment by switzel** [comment]
lanoxx,

Supporting your assessment that this is not an tilda issue, I noticed the following: if my laptop is connected to power supply then the problem doesn't occur. So it must be affected by power management and thus is probably related to hardware rendering (?). Still, do you maybe have an idea where to start looking for the problem?

**Comment by switzel** [comment]
I only just realized, that I wasn't actually using Compiz but Marco, and that the problem disappears with Compiz. So that answers the question where to start looking. I will write to the Marco-developers.

**Comment by lanoxx** [comment]
Closing this since its and old issue, the background feature has long been removed and this seemed to be window manager related anyway.
