### ISSUE TITLE
Port to vte-2.91 API

### ISSUE THREAD

**Issue by anatol** [lanoxx/tilda#94]
Gnome 3.14 has been released recently and it brought a new version of vte library (0.38). Some Linux distros are bringing this library version to their repos. This issue will track progress of porting to the new vte version.

I tried compiled tilda with new vte version and here is its output:

```
make  all-recursive
make[1]: Entering directory '/home/anatol/sources/tilda'
Making all in po
make[2]: Entering directory '/home/anatol/sources/tilda/po'
make[2]: Leaving directory '/home/anatol/sources/tilda/po'
make[2]: Entering directory '/home/anatol/sources/tilda'
  CC       src/src_tilda-callback_func.o
  CC       src/src_tilda-configsys.o
  CC       src/src_tilda-eggaccelerators.o
  CC       src/src_tilda-key_grabber.o
src/key_grabber.c: In function ‘tilda_window_set_active’:
src/key_grabber.c:129:5: warning: ‘gtk_widget_get_root_window’ is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkwidget.h:1025) [-Wdeprecated-declarations]
     Window x11_root_window = GDK_WINDOW_XID ( gtk_widget_get_root_window (tw->window) );
     ^
src/key_grabber.c:140:13: warning: ‘gtk_widget_get_root_window’ is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkwidget.h:1025) [-Wdeprecated-declarations]
             timestamp = gdk_x11_get_server_time(gtk_widget_get_root_window (tw->window));
             ^
  CC       src/src_tilda-tilda.o
src/tilda.c: In function ‘parse_cli’:
src/tilda.c:378:9: warning: ‘gdk_color_parse’ is deprecated (declared at /usr/include/gtk-3.0/gdk/deprecated/gdkcolor.h:79) [-Wdeprecated-declarations]
         if (gdk_color_parse(background_color, &col)) {
         ^
  CC       src/src_tilda-tilda_terminal.o
src/tilda_terminal.c: In function ‘status_line_changed_cb’:
src/tilda_terminal.c:236:5: warning: implicit declaration of function ‘vte_terminal_get_status_line’ [-Wimplicit-function-declaration]
     g_print ("Status = `%s'.\n", vte_terminal_get_status_line (VTE_TERMINAL(widget)));
     ^
src/tilda_terminal.c: In function ‘start_shell’:
src/tilda_terminal.c:457:9: warning: implicit declaration of function ‘vte_terminal_fork_command_full’ [-Wimplicit-function-declaration]
         ret = vte_terminal_fork_command_full (VTE_TERMINAL (tt->vte_term),
         ^
src/tilda_terminal.c: In function ‘tilda_term_config_defaults’:
src/tilda_terminal.c:612:5: warning: implicit declaration of function ‘vte_terminal_set_colors_rgba’ [-Wimplicit-function-declaration]
     vte_terminal_set_colors_rgba (VTE_TERMINAL(tt->vte_term), &fg, &bg, current_palette, TERMINAL_PALETTE_SIZE);
     ^
src/tilda_terminal.c:616:5: warning: implicit declaration of function ‘vte_terminal_set_visible_bell’ [-Wimplicit-function-declaration]
     vte_terminal_set_visible_bell (VTE_TERMINAL(tt->vte_term), config_getbool ("bell"));
     ^
src/tilda_terminal.c:623:5: warning: implicit declaration of function ‘vte_terminal_set_scroll_background’ [-Wimplicit-function-declaration]
     vte_terminal_set_scroll_background (VTE_TERMINAL(tt->vte_term), config_getbool ("scroll_background"));
     ^
src/tilda_terminal.c:632:5: warning: ‘gtk_widget_set_double_buffered’ is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkwidget.h:896) [-Wdeprecated-declarations]
     gtk_widget_set_double_buffered (tt->vte_term, config_getbool("double_buffer"));
     ^
src/tilda_terminal.c:679:5: warning: implicit declaration of function ‘vte_terminal_set_word_chars’ [-Wimplicit-function-declaration]
     vte_terminal_set_word_chars (VTE_TERMINAL(tt->vte_term), word_chars);
     ^
src/tilda_terminal.c:683:9: warning: implicit declaration of function ‘vte_terminal_set_background_image_file’ [-Wimplicit-function-declaration]
         vte_terminal_set_background_image_file (VTE_TERMINAL(tt->vte_term), config_getstr ("image"));
         ^
src/tilda_terminal.c:691:9: warning: implicit declaration of function ‘vte_terminal_set_background_saturation’ [-Wimplicit-function-declaration]
         vte_terminal_set_background_saturation (VTE_TERMINAL (tt->vte_term), transparency_level);
         ^
src/tilda_terminal.c:692:9: warning: implicit declaration of function ‘vte_terminal_set_opacity’ [-Wimplicit-function-declaration]
         vte_terminal_set_opacity (VTE_TERMINAL (tt->vte_term), (1.0 - transparency_level) * 0xffff);
         ^
src/tilda_terminal.c:693:9: warning: implicit declaration of function ‘vte_terminal_set_background_transparent’ [-Wimplicit-function-declaration]
         vte_terminal_set_background_transparent (VTE_TERMINAL(tt->vte_term), !tt->tw->have_argb_visual);
         ^
src/tilda_terminal.c: In function ‘popup_menu’:
src/tilda_terminal.c:815:5: warning: ‘gtk_action_group_new’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkactiongroup.h:175) [-Wdeprecated-declarations]
     action_group = gtk_action_group_new ("popup-menu-action-group");
     ^
src/tilda_terminal.c:818:5: warning: ‘gtk_action_new’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkaction.h:98) [-Wdeprecated-declarations]
     action = gtk_action_new ("new-tab", _("_New Tab"), NULL, GTK_STOCK_ADD);
     ^
src/tilda_terminal.c:818:5: warning: ‘GtkStock’ is deprecated [-Wdeprecated-declarations]
src/tilda_terminal.c:819:5: warning: ‘gtk_action_group_add_action_with_accel’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkactiongroup.h:203) [-Wdeprecated-declarations]
     gtk_action_group_add_action_with_accel (action_group, action, config_getstr("addtab_key"));
     ^
src/tilda_terminal.c:822:5: warning: ‘gtk_action_new’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkaction.h:98) [-Wdeprecated-declarations]
     action = gtk_action_new ("close-tab", _("_Close Tab"), NULL, GTK_STOCK_CLOSE);
     ^
src/tilda_terminal.c:822:5: warning: ‘GtkStock’ is deprecated [-Wdeprecated-declarations]
src/tilda_terminal.c:823:5: warning: ‘gtk_action_group_add_action_with_accel’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkactiongroup.h:203) [-Wdeprecated-declarations]
     gtk_action_group_add_action_with_accel (action_group, action, config_getstr("closetab_key"));
     ^
src/tilda_terminal.c:826:5: warning: ‘gtk_action_new’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkaction.h:98) [-Wdeprecated-declarations]
     action = gtk_action_new ("copy", NULL, NULL, GTK_STOCK_COPY);
     ^
src/tilda_terminal.c:826:5: warning: ‘GtkStock’ is deprecated [-Wdeprecated-declarations]
src/tilda_terminal.c:827:5: warning: ‘gtk_action_group_add_action_with_accel’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkactiongroup.h:203) [-Wdeprecated-declarations]
     gtk_action_group_add_action_with_accel (action_group, action, config_getstr("copy_key"));
     ^
src/tilda_terminal.c:830:5: warning: ‘gtk_action_new’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkaction.h:98) [-Wdeprecated-declarations]
     action = gtk_action_new ("paste", NULL, NULL, GTK_STOCK_PASTE);
     ^
src/tilda_terminal.c:830:5: warning: ‘GtkStock’ is deprecated [-Wdeprecated-declarations]
src/tilda_terminal.c:831:5: warning: ‘gtk_action_group_add_action_with_accel’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkactiongroup.h:203) [-Wdeprecated-declarations]
     gtk_action_group_add_action_with_accel (action_group, action, config_getstr("paste_key"));
     ^
src/tilda_terminal.c:834:5: warning: ‘gtk_action_new’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkaction.h:98) [-Wdeprecated-declarations]
     action = gtk_action_new ("fullscreen", _("Toggle fullscreen"), NULL, NULL);
     ^
src/tilda_terminal.c:835:5: warning: ‘gtk_action_group_add_action’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkactiongroup.h:200) [-Wdeprecated-declarations]
     gtk_action_group_add_action (action_group, action);
     ^
src/tilda_terminal.c:838:5: warning: ‘gtk_action_new’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkaction.h:98) [-Wdeprecated-declarations]
     action = gtk_action_new ("preferences", NULL, NULL, GTK_STOCK_PREFERENCES);
     ^
src/tilda_terminal.c:838:5: warning: ‘GtkStock’ is deprecated [-Wdeprecated-declarations]
src/tilda_terminal.c:839:5: warning: ‘gtk_action_group_add_action’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkactiongroup.h:200) [-Wdeprecated-declarations]
     gtk_action_group_add_action (action_group, action);
     ^
src/tilda_terminal.c:842:5: warning: ‘gtk_action_new’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkaction.h:98) [-Wdeprecated-declarations]
     action = gtk_action_new ("quit", NULL, NULL, GTK_STOCK_QUIT);
     ^
src/tilda_terminal.c:842:5: warning: ‘GtkStock’ is deprecated [-Wdeprecated-declarations]
src/tilda_terminal.c:843:5: warning: ‘gtk_action_group_add_action_with_accel’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkactiongroup.h:203) [-Wdeprecated-declarations]
     gtk_action_group_add_action_with_accel (action_group, action, config_getstr("quit_key"));
     ^
src/tilda_terminal.c:847:5: warning: ‘gtk_ui_manager_new’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkuimanager.h:130) [-Wdeprecated-declarations]
     ui_manager = gtk_ui_manager_new ();
     ^
src/tilda_terminal.c:848:5: warning: ‘gtk_ui_manager_insert_action_group’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkuimanager.h:138) [-Wdeprecated-declarations]
     gtk_ui_manager_insert_action_group (ui_manager, action_group, 0);
     ^
src/tilda_terminal.c:849:5: warning: ‘gtk_ui_manager_add_ui_from_string’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkuimanager.h:158) [-Wdeprecated-declarations]
     gtk_ui_manager_add_ui_from_string (ui_manager, menu_str, -1, &error);
     ^
src/tilda_terminal.c:860:5: warning: ‘gtk_ui_manager_get_widget’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkuimanager.h:149) [-Wdeprecated-declarations]
     menu = gtk_ui_manager_get_widget (ui_manager, "/ui/popup-menu");
     ^
  CC       src/src_tilda-tilda_window.o
  CC       src/src_tilda-tomboykeybinder.o
  CC       src/src_tilda-wizard.o
src/wizard.c: In function ‘check_enable_double_buffering_toggled_cb’:
src/wizard.c:777:9: warning: ‘gtk_widget_set_double_buffered’ is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkwidget.h:896) [-Wdeprecated-declarations]
         gtk_widget_set_double_buffered (GTK_WIDGET(tt->vte_term), status);
         ^
src/wizard.c: In function ‘check_terminal_bell_toggled_cb’:
src/wizard.c:792:9: warning: implicit declaration of function ‘vte_terminal_set_visible_bell’ [-Wimplicit-function-declaration]
         vte_terminal_set_visible_bell (VTE_TERMINAL(tt->vte_term), !status);
         ^
src/wizard.c: In function ‘validate_executable_command_cb’:
src/wizard.c:1005:9: warning: ‘gtk_entry_set_icon_from_stock’ is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkentry.h:276): Use 'gtk_entry_set_icon_from_icon_name' instead [-Wdeprecated-declarations]
         gtk_entry_set_icon_from_stock (GTK_ENTRY(w),
         ^
src/wizard.c:1007:13: warning: ‘GtkStock’ is deprecated [-Wdeprecated-declarations]
             GTK_STOCK_DIALOG_ERROR);
             ^
src/wizard.c:1014:9: warning: ‘gtk_entry_set_icon_from_stock’ is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkentry.h:276): Use 'gtk_entry_set_icon_from_icon_name' instead [-Wdeprecated-declarations]
         gtk_entry_set_icon_from_stock (GTK_ENTRY(w),
         ^
src/wizard.c: In function ‘entry_word_chars_changed’:
src/wizard.c:1054:9: warning: implicit declaration of function ‘vte_terminal_set_word_chars’ [-Wimplicit-function-declaration]
         vte_terminal_set_word_chars (VTE_TERMINAL(tt->vte_term), word_chars);
         ^
src/wizard.c: In function ‘check_enable_transparency_toggled_cb’:
src/wizard.c:1287:13: warning: implicit declaration of function ‘vte_terminal_set_background_saturation’ [-Wimplicit-function-declaration]
             vte_terminal_set_background_saturation (VTE_TERMINAL(tt->vte_term), transparency_level);
             ^
src/wizard.c:1288:13: warning: implicit declaration of function ‘vte_terminal_set_background_transparent’ [-Wimplicit-function-declaration]
             vte_terminal_set_background_transparent(VTE_TERMINAL(tt->vte_term), !tw->have_argb_visual);
             ^
src/wizard.c:1289:13: warning: implicit declaration of function ‘vte_terminal_set_opacity’ [-Wimplicit-function-declaration]
             vte_terminal_set_opacity (VTE_TERMINAL(tt->vte_term), (1.0 - transparency_level) * 0xffff);
             ^
src/wizard.c: In function ‘check_use_image_for_background_toggled_cb’:
src/wizard.c:1393:13: warning: implicit declaration of function ‘vte_terminal_set_background_image_file’ [-Wimplicit-function-declaration]
             vte_terminal_set_background_image_file (VTE_TERMINAL(tt->vte_term), image);
             ^
src/wizard.c: In function ‘combo_colorschemes_changed_cb’:
src/wizard.c:1496:13: warning: implicit declaration of function ‘vte_terminal_set_color_foreground_rgba’ [-Wimplicit-function-declaration]
             vte_terminal_set_color_foreground_rgba (VTE_TERMINAL(tt->vte_term), &gdk_text);
             ^
src/wizard.c:1497:13: warning: implicit declaration of function ‘vte_terminal_set_color_background_rgba’ [-Wimplicit-function-declaration]
             vte_terminal_set_color_background_rgba (VTE_TERMINAL(tt->vte_term), &gdk_back);
             ^
src/wizard.c: In function ‘combo_palette_scheme_changed_cb’:
src/wizard.c:1577:13: warning: implicit declaration of function ‘vte_terminal_set_colors_rgba’ [-Wimplicit-function-declaration]
             vte_terminal_set_colors_rgba (VTE_TERMINAL(tt->vte_term),
             ^
src/wizard.c: In function ‘check_scroll_background_toggled_cb’:
src/wizard.c:1757:9: warning: implicit declaration of function ‘vte_terminal_set_scroll_background’ [-Wimplicit-function-declaration]
         vte_terminal_set_scroll_background (VTE_TERMINAL(tt->vte_term), status);
         ^
  CC       src/src_tilda-xerror.o
/usr/bin/glib-compile-resources --generate src/glade-resources.gresource.xml --target=src/glade-resources.c --sourcedir=./src
  CC       src/src_tilda-glade-resources.o
  CCLD     src/tilda
/usr/bin/ld: src/src_tilda-tilda.o: undefined reference to symbol 'XSetErrorHandler'
/usr/lib/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:612: recipe for target 'src/tilda' failed
make[2]: *** [src/tilda] Error 1
sed -e 's|\@BINDIR\@|/usr/local/bin|' \
	-e 's|\@PIXMAPSDIR\@|/usr/local/share/pixmaps|' tilda.desktop.in > tilda.desktop
make[2]: Target 'all-am' not remade because of errors.
make[2]: Leaving directory '/home/anatol/sources/tilda'
Makefile:853: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/anatol/sources/tilda'
Makefile:486: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by egmontkob** [comment]
> The removal of transparency and background options from the latest VTE version is unfortunate

Just to clarify: Background image support was indeed removed. Transparent background is still available (for compositing WMs): just set a background color that has an alpha component, and set an argb visual for the app (see the unofficial gnome-terminal transparency patch in the Fedora and Ubuntu packages).

**Comment by egmontkob** [comment]
Note: vte-0.40 (gnome-3.16) is out.

The API is backwards compatible with 0.38. As an addition, it brings back the word-chars support which was dropped in 0.38.

Internally the biggest change is that the scrollback buffer's contents are written to the disk compressed and encrypted rather than in plaintext. This fixes a privacy issue that many people were concerned about, so it'd be great if you could port to the newest vte api (I'm not sure about the current state, I'm just copy-pasting this message :)).

**Comment by x2b** [comment]
Well, the X11 issue is because someone forgot to add the X11 flags to the linker. You could fix the situation like this: https://gist.github.com/x2b/faabb7e127a38984fd75

Porting the API remains a problem :)

**Comment by lanoxx** [comment]
That sounds reasonable. I just wonder why this always worked for me before. I could always compile tilda even without those flags.

**Comment by x2b** [comment]
@lanoxx  @egmontkob I have pushed a branch using the new API to my fork: https://github.com/x2b/tilda/tree/wip/vteport

So far I changed the following:

- background images are gone. This was done in VTE, maybe this was unfortunate but here we are. I removed the corresponding code from tilda
- transparency is still there, however it is set via the alpha channel of a GdkRGBA. Hence I have modified the the "Text Color" / "Background Color" color choosers to accept alpha values. These are passed to VTE so transparency still works.

Let me know what you think.

**Comment by pik** [comment]
@x2b I could be wrong - but I think a lot of people that use Tilda want the transparency feature, this is a definite regression.

**Comment by egmontkob** [comment]
> "Text Color" / "Background Color" color choosers to accept alpha values. 

Technically the text color also accepts an alpha channel (so that the same class is used everywhere), but it's ignored there. The foreground color can't be translucent, only the background.

As for the UI, I guess it'd be better to have a color picker that chooses a solid color, and a separate slider for transparency. But after all it's your choice

For me, transparency doesn't work after I quit and restart tilda. It goes back to the non-transparent version of the same color.

> gtkwidget.c:13153: widget class `VteTerminal' has no property named `inner-border'

This was renamed to the 'padding' property with css-like values along with units, e.g. "1px 3px 1px 1px"

**Comment by pik** [comment]
Here is an update of the vte-port with the transparency regression restored. https://github.com/pik/tilda/tree/vte_port

I don't really like some things that are going on here - for example vte-2.91 changed their `vte_terminal_set_colors_rgba` to standard `colors` deprecating the old ones. But GTK is still using `rgba` namespaces for their functions i.e. `gtk_color_chooser_get_rgba`, this is a confusing inconsistency. 

Also since the transparency options were deprecated using `vte_terminal_set_color_background` requires fetching all the color values from config i.e. 
```
    gboolean status = !config_getbool ("enable_transparency");
    bg.red   =    GUINT16_TO_FLOAT(config_getint ("back_red"));
    bg.green =    GUINT16_TO_FLOAT(config_getint ("back_green"));
    bg.blue  =    GUINT16_TO_FLOAT(config_getint ("back_blue"));
    bg.alpha =    (status ? GUINT16_TO_FLOAT(config_getint ("back_alpha")) : 1.0);
``` 
That's four locked reads on the config file when really there should only be one - but `vte` does not give an option of obtaining the background color or only updating `bg.alpha`. 

@x2b I used your monitor switching-code, but it still needs work, for example the Tilda-window disappears when wizard is called and doesn't reappear when wizard is closed. Also the the pull-down key does not pull-up the tilda window if it's unfocused.

**Comment by x2b** [comment]
Regarding `tilda_window_set_active`: comments say

    /* This function will make sure that tilda window becomes active (gains
     * the focus) when it is called.
     *
     * This has to be the worst possible way of making this work, but it was the
     * only way to get metacity to play nicely. All the other WM's are so nice,
     * why oh why does metacity hate us so?
     */
    void tilda_window_set_active (tilda_window *tw)

This may have been slightly broken before already...

**Comment by lanoxx** [comment]
I never really investigated this. That comment was already in the legacy codebase of tilda. Given the recent changes and bugfixes in the metacity code it might not even be valid anymore. Do you think something should be changed here?

**Comment by pik** [comment]
So I seem to have fixed the bug with `tilda_window_set_active` hanging https://github.com/pik/tilda/commit/01dd9dc4db79a9041b9eb35f8ec99552b35dc802 -- apparently (from the gdk docs): ```gdk_x11_get_server_time ()```

>a GdkWindow, used for communication with the server. The window must have GDK_PROPERTY_CHANGE_MASK in its events mask or a hang will result. 

Although I guess no one had that problem before? 

Also replaced `inner-border` `border.bottom` with `margin-bottom` for the https://github.com/pik/tilda/commit/812742bdfa2c4a2fe8aaf12cbcd6e73bdc35a6ac#diff-cb2af9d3deba6ff278bbe00e78fafbc4L895

**Comment by lanoxx** [comment]
@x2b I have added the X11 flags to configure.

**Comment by lanoxx** [comment]
Hi @pik,

thanks for working on this. However I am not entirely happy with merging this yet. Most importantly this will mean that tilda can no longer be compiled on older systems where only VTE 2.90 is available. Especially the current Ubuntu LTS, I would like to stay at least compatible with 14.04, because I am sure some people are compiling from source and want to run tilda on older systems.

I think there are two options to go forward with this:

 1. Either we wait until VTE 2.90 has enough widespread support and then merge this. This is not a good solution for users who want to use the new API now.
 2. Alternatively we need to create a patch that allows conditional compilation for both VTE 2.90 and 2.91, this is my preferred solution. In this case I would prefer to default to VTE 2.90 and allow compiling for VTE 2.91 with a compile time option. With this options distributions could also possibly provide two packages for the different VTE versions.
 3. Even cooler would be to detect the library version at runtime and use either 2.90 or 2.91 depending on whats available.  Then distributions would only need to ship one binary. But I guess that would be quite complicated, therefore I think option 2 is the best choice.

In any case given the uncertainty about terminal transparency and other options I do not want to completely remove support for VTE 2.90 any time soon. Also note that it is possible to install VTE 2.90 and 2.91 at the same time on a system, so it is possible to continue to use tilda even on newer systems.

**Comment by pik** [comment]
@lanoxx 
Yes that makes sense, options 2) or 3) are definitely preferable. Is it okay to remove features lacking in 2.91 from the 2.90 compatible version as well? 

> In any case given the uncertainty about terminal transparency

It seems to work okay with background.alpha, but idk if there are other reasons to be worried? 

I guess my main concern  overall would be taking time to setup cross-compatibility between 2.90/2.91 and then have more breaking changes in 2.92 or in the nearer future.

**Comment by lanoxx** [comment]
> Is it okay to remove features lacking in 2.91 from the 2.90 compatible version as well? 
No. Add a condition and keep them available in 2.90.

> It seems to work okay with background.alpha, but idk if there are other reasons to be worried? 

Yes, right now. But the developer also made it clear to me that he will remove features if they make the code too complex and he thinks they are not necessary, and he has clearly stated to me that he thinks transparency is very unnecessary. So I am just not convinced that it will stay that way. I am also not very fond of the fact that features which people are actually using are just removed because the developer finds them not useful. I am also not very fond of the fact that features are removed just to bring them back in the next version, for example note that the `word_chars` feature which was removed in 0.38 is actually back in version 0.40 as far as I know.

**Comment by egmontkob** [comment]
Yet another option could be to maintain two branches of tilda: work actively for vte-2.91 (let's say tilda 1.3.x) and keep backporting the more important changes to the vte-2.90 based branch (tilda-1.2.x). I guess you could abadon the old branch in about a year from now when the next Ubuntu LTS is released.

Re option 3: It's probably way too complicated and I can't see the point in it.

Re option 2: I'm quite certain no distribution will want to ship two versions of tilda in parallel, and that if they can choose, they'd probably choose to link against newer vte.

Newest vte is in almost all aspects superior to the old ones (maybe background image being the only notable exception), just look at the changelog how many significant improvements it has received, and it's still actively being worked on. I see no point in you preferring 2.90 over 2.91. IMO the default should be 2.91, falling back to 2.90 for compatibility on systems where the new one is not yet available.

**Comment by Justinzobel** [comment]
Any update on this issue? Trying to package for Solus but we have 2.91, not 2.90

**Comment by anatol** [comment]
I am an Arch developer and we would like to see a few remaining packages (like tilda) moved to the latest stable vte release (2.91). Is there any chance to see the fix merged/released?

**Comment by lanoxx** [comment]
Yes its actually mostly finished, I just did not have the time to merge it into master and a few last changes that I have in mind. Maybe I can find some spare time this weekend or next.

**Comment by anatol** [comment]
Great, thanks you for doing this. Looking forward for a new release with the latest VTE support.
