### ISSUE TITLE
Behaviour of "center horizontally" with multiple monitors

### ISSUE THREAD

**Issue by stevenhoneyman** [lanoxx/tilda#97]
With dual screens, ticking the "center horizontally" option does exactly what it says... and centers Tilda. The trouble is, that means half is on one monitor, and half is on another!

The expected behaviour (as I see it anyway) would be center on the monitor chosen under "Select monitor"

**Comment by dschwoerer** [comment]
What window-manager do you use?

**Comment by stevenhoneyman** [comment]
Openbox (whatever the latest git version is at)

**Comment by x2b** [comment]
I can confirm the problem with gdm / gnome3.

**Comment by lanoxx** [comment]
I pushed a modified version of you fix. Please test it. There is another change required for fix switching the active monitor which centering is active. Currently this still ignores the centering option. @x2b  Thanks for the initial patch.
